
export const QUEST_DATA_SPACE_EN = {
    givers: [
        { text: "A three-eyed alien ambassador", type: "official", gender: "m" },
        { text: "A Starfleet captain", type: "official", gender: "f" },
        { text: "A cyborg mercenary with rusted implants", type: "soldier", gender: "m" },
        { text: "An AI projecting itself as a child", type: "construct", gender: "u" },
        { text: "A xenobiologist fascinated by slime", type: "scholar", gender: "m" },
        { text: "A smuggler mentioning the 'Kessel Run'", type: "rogue", gender: "m" },
        { text: "The matriarch of a dying planet", type: "noble", gender: "f" },
        { text: "A robot trying to simulate feelings", type: "construct", gender: "m" },
        { text: "A miner from an asteroid belt", type: "civilian", gender: "m" },
        { text: "A bounty hunter in Mandalorian armor", type: "soldier", gender: "f" },
        { text: "A technopriest anointing machines", type: "cleric", gender: "m" },
        { text: "A pilot claiming to have seen Earth", type: "civilian", gender: "m" },
        { text: "A creature made of pure energy", type: "elemental", gender: "u" },
        { text: "The space station administrator", type: "official", gender: "m" },
        { text: "A telepath reading minds", type: "mage", gender: "m" },
        { text: "A navigator who hears the stars sing", type: "mage", gender: "m" },
        { text: "A rogue scientist", type: "scholar", gender: "f" },
        { text: "A dealer in exotic genetics", type: "merchant", gender: "m" },
        { text: "The last survivor of a dead star", type: "noble", gender: "f" },
        { text: "A droid believing itself to be a god", type: "construct", gender: "m" },
        { text: "A soldier of the Galactic Guard", type: "soldier", gender: "m" },
        { text: "A hacker controlling the network", type: "rogue", gender: "f" },
        { text: "A monk worshipping the Void", type: "cleric", gender: "m" },
        { text: "A weaponsmith for illegal plasma guns", type: "craftsman", gender: "m" },
        { text: "The hostess of the 'Restaurant at the End of the Universe'", type: "civilian", gender: "f" },
        { text: "A time traveler who arrived on the wrong day", type: "scholar", gender: "m" },
        { text: "A clone searching for his original DNA", type: "civilian", gender: "m" },
        { text: "A shapeshifter who forgot her form", type: "monster", gender: "f" },
        { text: "A scavenger in a space suit", type: "rogue", gender: "m" },
        { text: "A psionic shattering glass with her mind", type: "mage", gender: "f" },
        { text: "An admiral planning a coup", type: "official", gender: "m" },
        { text: "The keeper of the galactic zoo", type: "druid", gender: "m" },
        { text: "An invisible assassin", type: "rogue", gender: "m" },
        { text: "An archaeologist for pre-warp civilizations", type: "scholar", gender: "f" },
        { text: "A pilot whose ship is alive", type: "civilian", gender: "m" },
        { text: "A mutant from the lower levels", type: "monster", gender: "m" },
        { text: "The voice of the ship's computer (hologram)", type: "construct", gender: "f" },
        { text: "A diplomat speaking only in riddles", type: "official", gender: "m" },
        { text: "A battlefield scavenger", type: "rogue", gender: "f" },
        { text: "A man awakened from cryo-sleep (after 1000 years)", type: "civilian", gender: "m" },
        { text: "A being made of crystals", type: "elemental", gender: "u" },
        { text: "The mechanic working miracles", type: "craftsman", gender: "m" },
        { text: "An Imperial spy", type: "soldier", gender: "f" },
        { text: "A priest of the Machine God", type: "cleric", gender: "m" },
        { text: "A gambler with a cybernetic eye", type: "rogue", gender: "m" }
    ],
    items: [
        "an unstable plasma core", "the hyperdrive key", "an ancient Jedi artifact",
        "an encrypted data disc", "a sample of 'Xenomorph slime'", "a communicator receiving only static",
        "the Death Star blueprints (Part 1)", "a phase blaster", "a bottle of Romulan Ale",
        "a meteorite shard", "an android's neuro-chip", "a map of the Unknown Regions",
        "a holocron", "a battery that lasts forever", "a vacuum suit",
        "a live Tribble", "a universal translator", "a piece of Dark Matter",
        "a lightsaber (damaged)", "a cube showing holographic maps", "a gravity generator",
        "the black box of a lost ship", "a vial of nanobots", "a dead soldier's helmet",
        "a singing crystal", "a gun needing no ammo", "a portable force field",
        "a medkit from the future", "a book of real paper (extremely valuable)", "a seed of an alien tree",
        "a glove controlling electricity", "a ring that teleports (randomly)", "a can of 'Real Air'",
        "a joystick made of gold", "a droid head (still talking)", "a crate of antimatter (careful!)",
        "Permit A38", "an enemy uniform", "a scanner detecting lies",
        "a piece of hull armor (indestructible?)", "an alien larva in a jar", "a dagger of light",
        "an implant storing memories", "a star map made of glass", "a ring of neutronium"
    ],
    locations: [
        "on Moonbase Alpha", "in orbit around Saturn", "in the wreck of the colony ship",
        "on the desert planet", "in the Restaurant at the End of the Universe", "in the engine room",
        "on the cruiser's bridge", "in the zero-gravity chamber", "inside the wormhole",
        "in the asteroid field", "at the xenobiology station", "in Hangar 18",
        "on the ice planet Hoth (similar)", "in the biosphere", "in the replicator room",
        "in the medical bay", "in the cargo hold", "in the transporter room",
        "in the airlock", "in the reactor core", "on the observation deck",
        "in the mines of the Red Planet", "in the Nebula of Terror", "on a Dyson Sphere",
        "in the abandoned space station", "in the hyperspace tunnel", "in the Junkyard of the Stars",
        "in the Library of Alexandria (Digital)", "in the simulator room", "in the officers' mess",
        "on the surface of a comet", "at the center of the galaxy", "at the event horizon",
        "in the Utopia Planitia shipyards", "in the quarantine zone", "in the escape pod",
        "in the market of Coruscant (similar)", "in Cloud City", "in the swamp of Dagobah (similar)",
        "in the gladiator arena", "in the madman's lab", "in the Death Star control room",
        "in the clone barracks", "in the ventilation shaft", "under the surface of the ice moon"
    ],
    targets: [
        "the Swarm Queen", "a rogue AI", "the Smuggler King",
        "a shapeshifter", "the Emperor", "a space pirate",
        "the black hole (prevent collapse)", "an alien spore", "the traitor on board",
        "a hostile fleet", "the First Officer", "a time traveler",
        "the bounty hunter", "the alien baby", "the mad scientist",
        "the Grand Admiral", "the symbiote", "the cyborg ninja",
        "the hacker 'Ghost'", "the guardian drone", "the last Jedi (or Sith?)",
        "the Merchant of Death", "the spy", "the diplomat",
        "the mothership", "the Planet Eater", "the Star Walker",
        "the Oracle", "the Warlord", "the Borg Queen (similar)",
        "the clone warrior", "Experiment 626", "the scavenger",
        "the telepath", "the Invisible One"
    ],
    task_templates: [
        "to retrieve ##Item## ##Location##",
        "to calibrate the sensors ##Location##",
        "to make first contact with ##Target## ##Location##",
        "to scan ##Item## ##Location##",
        "to neutralize ##Target## ##Location##",
        "to solve a diplomatic crisis with ##Target## ##Location##",
        "to save ##Item## ##Location## from self-destruction",
        "to investigate a distress signal ##Location##",
        "to throw ##Target## out the airlock ##Location##",
        "to throw ##Item## into the reactor ##Location##",
        "to activate the shields ##Location##",
        "to calculate the course ##Location##",
        "to extract (beam up) ##Target## ##Location##",
        "to restore communication with ##Target## ##Location##",
        "to sabotage ##Item## ##Location##",
        "to save ##Target## ##Location## from a vacuum leak",
        "to hack the code for ##Item## ##Location##",
        "to clone (or prevent cloning of) ##Target## ##Location##",
        "to stop an invasion by ##Target## ##Location##",
        "to launch ##Item## ##Location## into hyperspace",


        // --- Social / Intrigue ---
        "to provoke a diplomatic scandal with ##Target## ##Location##",
        "to disguise as a Starfleet officer to deceive ##Target## ##Location##",
        "to forge a secret alliance with ##Target## ##Location##",
        "to intercept communications from ##Target## ##Location##",
        "to persuade ##Target## ##Location## to switch sides",
        "to sabotage a peace treaty ##Location##",


        // --- Reverse / Morally Grey ---
        "to hide contraband ##Location## to implicate ##Target##",
        "to commit sabotage ##Location## and blame ##Target##",
        "to steal the emergency rations ##Location##",
        "to betray ##Target## ##Location## to bounty hunters",
        "to release a dangerous alien ##Location##",
        "to let the oxygen run low ##Location##",


        // --- Detective / Mystery ---
        "to decrypt the logbook of ##Item## ##Location##",
        "to trace the origin of the distress signal ##Location##",
        "to analyze the biochemical traces of ##Target## ##Location##",
        "to find out who sabotaged the reactor ##Location##",
        "to solve the mystery of the missing crew ##Location##",
        "to investigate a time paradox ##Location##",


        // --- Space Specific (Tech & Void) ---
        "to repair the warp drive ##Location## with ##Item##",
        "to stabilize a black hole ##Location##",
        "to modulate the shields of ##Location## to block radiation",
        "to initiate a terraforming protocol ##Location##",
        "to restore gravity ##Location##",
        "to plot a new course for an asteroid ##Location##",
        "to free the AI ##Location## from a logic error",
        "to recover an ancient relic ##Location## before it decays",
        "to log the first contact with a new species ##Location##",
        "to win a race through an asteroid field ##Location##",
        "to survive a solar storm ##Location##",
        "to seal the quarantine station ##Location##",
        "to map a wormhole ##Location##",
        "to scan a Dyson Sphere ##Location##",
        "to reboot the ship's computer ##Location## (manually)",
        "to peacefully end a droid rebellion ##Location##",
        "to patch a vacuum leak ##Location## with improvised means",
        "to find the coordinates of 'Lost Earth' ##Location##"
    ],
    reasons: [
        { text: "for the Federation" },
        { text: "to end the war" },
        { text: "to discover new worlds" },
        { text: "because the computer calculated it" },
        { text: "to save the galaxy" },
        { text: "for credits" },
        { text: "to phone home" },
        { text: "because oxygen is running low" },
        { text: "to protect the timeline" },
        { text: "against the Empire" },
        { text: "out of scientific curiosity" },
        { text: "to avoid First Contact" },
        { text: "because the prophecy says so" },
        { text: "to impress the Captain" },
        { text: "to avoid punishment" },
        { text: "because the warp core is breaching" },
        { text: "to save the species" },
        { text: "for revenge for Alderaan" }
    ],
    incidents: [
        { text: "Sensors are going crazy" },
        { text: "Shields at 20%" },
        { text: "Intruder alert!" },
        { text: "Gravity is failing" },
        { text: "A wormhole is opening" },
        { text: "Three moons are in conjunction" },
        { text: "The computer is singing 'Daisy Bell'" },
        { text: "An unknown signal is being received" },
        { text: "Reality is flickering (Holodeck error)" },
        { text: "Time loop detected" },
        { text: "Oxygen levels are dropping" },
        { text: "Aliens are on board" },
        { text: "Reactor going critical" },
        { text: "The AI is rebelling" },
        { text: "An asteroid shower hits the ship" },
        { text: "The crew is hallucinating" }
    ],
    deadlines: [
        { text: "before oxygen runs out" },
        { text: "before the warp core breaches" },
        { text: "in 10 standard minutes" },
        { text: "before the supernova explodes" },
        { text: "before the fleet arrives" },
        { text: "before shields fail" },
        { text: "before the countdown ends" },
        { text: "while the portal is open" },
        { text: "before life support fails" },
        { text: "when the solar eclipse begins" },
        { text: "before the virus spreads" }
    ]
};
