
export const QUEST_DATA_CYBERPUNK_DE = {
    givers: [
        { text: "Ein Fixer mit verchromtem Arm und Sonnenbrille", type: "rogue", gender: "m" },
        { text: "Eine Netrunnerin, die nur über Avatare spricht", type: "scholar", gender: "f" },
        { text: "Ein Konzern-Executive, der nervös wirkt", type: "official", gender: "m" },
        { text: "Ein Street-Doc mit blutiger Schürze", type: "cleric", gender: "m" },
        { text: "Eine Nomad-Anführerin auf einem Hover-Bike", type: "ranger", gender: "f" },
        { text: "Ein KI-Konstrukt eines toten Rockstars", type: "undead", gender: "m" },
        { text: "Ein Polizei-Detective, der zu viel weiß", type: "official", gender: "m" },
        { text: "Ein Drogendealer mit synthetischen Augen", type: "rogue", gender: "m" },
        { text: "Eine Journalistin, die einen Skandal aufdeckt", type: "civilian", gender: "f" },
        { text: "Ein Techie, der alles reparieren kann", type: "craftsman", gender: "m" },
        { text: "Ein gefallener Idol-Star mit Bodyguards", type: "artist", gender: "f" },
        { text: "Ein Söldner, der nur für Eurodollar arbeitet", type: "soldier", gender: "m" },
        { text: "Ein Taxi-KI, die philosophische Fragen stellt", type: "construct", gender: "x" },
        { text: "Ein Schwarzmarkt-Chirurg ohne Lizenz", type: "healer", gender: "m" },
        { text: "Eine Konzern-Erbin auf der Flucht", type: "noble", gender: "f" },
        { text: "Ein alter Hacker, der noch mit Tastatur arbeitet", type: "scholar", gender: "m" },
        { text: "Ein Barkeeper, der jedes Geheimnis kennt", type: "civilian", gender: "m" },
        { text: "Eine Cyborg-Kriegerin auf Rachefeldzug", type: "soldier", gender: "f" },
        { text: "Ein Müllsammler, der wertvolle Daten findet", type: "commoner", gender: "m" },
        { text: "Ein Hologramm-Künstler mit versteckten Botschaften", type: "artist", gender: "m" },
        { text: "Eine Schmugglerin für echte Lebensmittel", type: "rogue", gender: "f" },
        { text: "Ein abtrünniger Sicherheits-Droide", type: "construct", gender: "x" },
        { text: "Ein Untergrund-Priester der Neon-Kirche", type: "cleric", gender: "m" },
        { text: "Eine Konzern-Wissenschaftlerin mit Gewissen", type: "scholar", gender: "f" },
        { text: "Ein Gang-Boss mit goldenen Zähnen", type: "criminal", gender: "m" },
        { text: "Ein Informations-Broker im Deep Net", type: "rogue", gender: "x" },
        { text: "Eine Straßenfegerin, die alles sieht", type: "commoner", gender: "f" },
        { text: "Ein Ex-Militär, der jetzt als Türsteher arbeitet", type: "soldier", gender: "m" },
        { text: "Ein illegaler Klon eines Prominenten", type: "clone", gender: "x" },
        { text: "Eine Hackerin, die nur in Code spricht", type: "scholar", gender: "f" },
        { text: "Ein Waffenhändler für experimentelle Tech", type: "merchant", gender: "m" },
        { text: "Ein Kurier, der niemals Fragen stellt", type: "rogue", gender: "m" },
        { text: "Eine Aktivistin gegen Cyber-Implantate", type: "civilian", gender: "f" },
        { text: "Ein virtuelles Idol, das ein Bewusstsein entwickelt hat", type: "construct", gender: "f" },
        { text: "Ein alter Yakuza-Oyabun im Exil", type: "noble", gender: "m" },
        { text: "Ein Straßenkind mit einem teuren Daten-Chip", type: "child", gender: "x" },
        { text: "Eine Biologin, die illegale Pflanzen züchtet", type: "scholar", gender: "f" },
        { text: "Ein Barkeeper im 'Afterlife'", type: "merchant", gender: "m" },
        { text: "Ein Ripperdoc, der Schulden eintreibt", type: "healer", gender: "m" },
        { text: "Eine Konzern-Spionin in Tarnung", type: "rogue", gender: "f" },
        { text: "Ein Mech-Pilot ohne Mech", type: "soldier", gender: "m" },
        { text: "Eine KI, die einen Körper sucht", type: "construct", gender: "x" },
        { text: "Ein Dealer für 'Braindance'-Chips", type: "criminal", gender: "m" },
        { text: "Eine Untergrund-Rennfahrerin", type: "rogue", gender: "f" },
        { text: "Ein Sicherheitschef, der gefeuert wurde", type: "soldier", gender: "m" },
        { text: "Ein Hacker-Kollektiv (Hive-Mind)", type: "group", gender: "x" },
        { text: "Eine alte Frau, die noch echte Bücher liest", type: "scholar", gender: "f" },
        { text: "Ein Mutant aus der Kanalisation", type: "monster", gender: "m" },
        { text: "Ein Konzern-Auditor 'für spezielle Probleme'", type: "official", gender: "m" },
        { text: "Ein Barkeeper, der eigentlich ein Schläfer-Agent ist", type: "rogue", gender: "m" }
    ],
    items: [
        "einen experimentellen Bio-Chip", "ein Cyberdeck 'Arasaka MK-IV'", "eine Daten-Splitter mit Beweisen",
        "eine Flasche echten Tequila (unbezahlbar)", "den Prototyp einer neuen Waffe", "einen Koffer voller Eurodollar",
        "die Zutrittskarte für Ebene 99", "ein kybernetisches Auge", "eine gestohlene Identität",
        "ein 'Schwarzes Eis' Virus-Programm", "eine Drohne mit KI", "ein synthetisches Organ (Herz)",
        "die Codes für den Orbitallift", "ein Mem-Stick aus der alten Zeit", "eine Kiste echte Äpfel",
        "ein Neuro-Implantat mit Militär-Software", "die Baupläne für einen EMP-Generator", "ein Ticket für die Mars-Kolonie",
        "eine antike Pistole (Projektilwaffe)", "ein gehacktes Polizeifunkgerät", "eine Dosis 'Eternity'-Droge",
        "den Kopf eines Androiden (spricht noch)", "eine Festplatte mit kompromittierenden Daten", "einen Schlüssel zu einem Schließfach",
        "eine Tarnvorrichtung (Prototyp)", "ein Nanobot-Injektor", "eine Kiste mit illegalen Cyber-Gliedmaßen",
        "ein Virus, der Bankkonten leert", "eine Aufzeichnung eines geheimen Treffens", "ein Zugangscode für das Stromnetz",
        "eine selteneVinyl-Schallplatte", "ein Stück echter Himmel (Hologramm)", "ein gefälschter Reisepass",
        "eine Smart-Gun mit eigener Persönlichkeit", "ein Koffer mit nuklearem Zünder", "eine DNS-Probe eines CEOs",
        "ein Backup des Bewusstseins einer toten Person", "eine Karte der alten U-Bahn-Tunnel", "ein Störsender für Überwachungskameras",
        "ein bionischer Arm mit versteckter Klinge", "eine Dose Katzenfutter (Luxusgut)", "ein Chip mit verbotener Musik",
        "eine VR-Brille mit direktem Neural-Link", "ein Passwort für eine Satelliten-Waffe", "eine Probe eines tödlichen Virus",
        "ein Koffer mit Diamanten (synthetisch)", "eine Liste von Schläfer-Agenten", "ein Gerät zum Hacken von Automaten",
        "eine Jacke mit kugelsicherer Verwebung", "ein Motorrad mit Jet-Antrieb", "ein Daten-Würfel der ersten KI"
    ],
    locations: [
        "in Night City (Sektor 7)", "im Neon-Slum 'The Sprawl'", "im Penthouse des Megatowers",
        "in einer illegalen Ripperdoc-Klinik", "im Cyberspace (Deep Net)", "in der U-Bahn-Station",
        "im Hinterzimmer der Noodle-Bar", "in der verlassenen Fabrik", "im Konzern-Hauptquartier",
        "im Daten-Fortress", "auf dem Schwarzmarkt", "in der Bio-Farm",
        "im Rotlichtviertel", "auf dem Schrottplatz", "in der VR-Spielhalle",
        "im Keller des Nachtclubs", "auf dem Dach eines Wolkenkratzers", "in der Müllverbrennungsanlage",
        "im Serverraum bei Null-Temperatur", "in der Quarantäne-Zone", "im Frachtcontainer am Hafen",
        "in der Kanalisation", "im Wartezimmer des Trauma-Teams", "in der Lobby des Grand Hotels",
        "auf der Autobahnbrücke", "im verlassenen Einkaufszentrum", "in der Orbital-Station (per Link)",
        "im geheimen Bunker unter der Stadt", "in der Produktionshalle für Androiden", "im hydroponischen Garten",
        "in der Waffenkammer der Polizei", "im Unterschlupf der Nomaden", "in der Einsatzzentrale",
        "im Labor für Cybergenetik", "in der Spielhölle der Yakuza", "im verregneten Hinterhof",
        "in der Kapsel-Wohnung", "im Aufzug zum Orbit", "in der Recycling-Anlage für Cyberware",
        "im VIP-Bereich des Clubs", "in der Leichenhalle", "im Taxi, das im Kreis fährt",
        "in der No-Go-Zone", "im Kernkraftwerk am Stadtrand", "in der virtuellen Bibliothek",
        "im Holodeck", "in der Waffenfabrik", "im unterirdischen Highway",
        "in der Drohnen-Ladestation", "im Büro des Bürgermeisters", "in der Aschewüste vor der Stadt"
    ],
    targets: [
        "eine abtrünnige KI", "den CEO von Militech", "einen Cyberpsycho",
        "einen rivalisierenden Netrunner", "die Yakuza-Chefin", "einen korrupten Cop",
        "einen Konzern-Attentäter", "den Anführer der 'Chrom-Legion'", "einen Whistleblower",
        "ein synthetisches Klon-Wesen", "den Bürgermeister", "einen berüchtigten Hacker",
        "die Sicherheits-Drohne 'Alpha'", "einen verrückten Ripperdoc", "den Dealer an der Ecke",
        "eine virtuelle Popstar-KI", "den Chef der Müllabfuhr-Mafia", "einen Konzern-Anwalt",
        "einen Industriespion", "den Anführer der Technik-Sekte", "einen entflohenen Androiden",
        "den Wächter des Daten-Kerns", "einen Schwarzmarkt-Chirurgen", "den Besitzer des Nachtclubs",
        "einen Söldnerführer", "eine Biowaffe auf zwei Beinen", "den Architekten der Matrix",
        "einen Geist im System", "die Tochter des Konzern-Chefs", "einen außer Kontrolle geratenen Panzer",
        "den Meister-Dieb", "einen radikalen Aktivisten", "den letzten echten Menschen",
        "ein Rudel Cyber-Hunde", "den Operator der Überwachung", "einen Nano-Schwarm",
        "den Piloten des Transport-Shuttles", "einen genetisch modifizierten Tiger", "den Verwalter des Blocks",
        "einen korrupten Richter", "den Anführer der Scavenger", "einen Tech-Schamanen",
        "den Wirt des Virus", "einen unsichtbaren Attentäter", "den Konstrukteur der Bombe",
        "eine lebende Bombe", "den Kurier mit dem Code", "das Orakel des Netzes"
    ],
    task_templates: [
        "##Item## ##Location## aus dem Netz zu hacken",
        "##Target## ##Location## zu extrahieren (Kidnapping?)",
        "##Item## ##Location## zu schmuggeln, ohne gescannt zu werden",
        "einen Virus ##Location## hochzuladen",
        "##Target## ##Location## zu 'nullifizieren'",
        "Informationen über ##Target## ##Location## zu beschaffen",
        "einen Deal mit ##Target## ##Location## zu überwachen",
        "##Item## ##Location## vor den Konzern-Truppen zu bergen",
        "das Sicherheitssystem ##Location## zu sabotieren",
        "##Target## ##Location## vor einem Cyber-Angriff zu schützen",
        "die Identität von ##Target## ##Location## zu löschen",
        "##Item## ##Location## an den Höchstbietenden zu verkaufen",
        "##Target## ##Location## zu beschatten",
        "einen Wanze bei ##Target## ##Location## zu platzieren",
        "##Item## ##Location## zur Explosion zu bringen",
        "##Target## ##Location## aus dem Gefängnis zu befreien",
        "den Server ##Location## zu überhitzen",
        "##Item## ##Location## zu replizieren",
        "##Target## ##Location## ein Geständnis zu entlocken",
        "den Transport für ##Item## ##Location## zu überfallen",
        "##Target## ##Location## vor den Yakuza zu verstecken",
        "##Item## ##Location## zu entschlüsseln",
        "einen Hinterhalt für ##Target## ##Location## zu legen",
        "##Target## ##Location## zu erpressen",
        "das Netzwerk ##Location## lahmzulegen",
        "##Item## ##Location## gegen eine Fälschung auszutauschen",
        "##Target## ##Location## zu einer Falle zu locken",
        "die Firewall ##Location## zu durchbrechen",
        "##Item## ##Location## im Müll zu finden",
        "##Target## ##Location## zu diskreditieren (Fake News)",
        "den Strom ##Location## abzuschalten",
        "##Item## ##Location## zu stehlen",


        // --- Social / Intrigue ---
        "ein falsches Gerücht über ##Target## im Neuro-Netz zu verbreiten",
        "sich als Techniker zu tarnen, um ##Target## ##Location## zu überwachen",
        "einen verschlüsselten Daten-Splitter an ##Target## ##Location## zu übergeben",
        "##Target## ##Location## bei einem Treffen mit den Triaden zu belauschen",
        "den Ruf von ##Target## im Data-Pool zu terminieren",
        "eine Desinformationskampagne gegen ##Target## ##Location## zu starten",
        "##Target## ##Location## dazu zu bringen, die Zugangscodes zu verraten",


        // --- Reverse / Morally Grey ---
        "gefälschte Beweise ##Location## zu platzieren, um ##Target## zu belasten",
        "einem Cyberpsycho ##Location## zu helfen, der Polizei zu entkommen",
        "die Medikamente für das Waisenhaus ##Location## zu stehlen",
        "##Target## ##Location## mit sensiblen Daten zu erpressen",
        "einen Systemausfall ##Location## zu verursachen, um Spuren zu verwischen",
        "einen illegalen Deal ##Location## zu beschützen",
        "##Target## ##Location## an einen Konzern zu verkaufen",


        // --- Detective / Mystery ---
        "die digitale Signatur von ##Target## ##Location## zu analysieren",
        "den Maulwurf im Konzern ##Location## zu identifizieren",
        "den virtuellen Tatort ##Location## zu rekonstruieren",
        "die Verbindungsdaten von ##Target## ##Location## zu hacken",
        "herauszufinden, wer den Virus ##Location## programmiert hat",
        "die Quelle des Signals ##Location## zu triangulieren",
        "ein korruptes File ##Location## wiederherzustellen",


        // --- Cyberpunk Specific (Hacking & Tech) ---
        "einen Dämon in das Subnetz von ##Location## zu injizieren",
        "die Cyberware von ##Target## ##Location## fernzusteuern",
        "einen 'Black ICE' Angriff ##Location## zu überleben",
        "das Bewusstsein von ##Target## ##Location## auf einen Chip zu laden",
        "eine illegale Braindance-Aufnahme ##Location## zu sichern",
        "die Firmware von ##Item## ##Location## zu überschreiben",
        "einen Konzern-Server ##Location## physisch zu zerstören",
        "eine KI ##Location## aus ihrer Sandbox zu befreien",
        "ein fliegendes Taxi ##Location## zu hacken und umzuleiten",
        "eine Cyber-Prothese ##Location## zu reparieren, bevor sie explodiert",
        "einen Memory-Wipe bei ##Target## ##Location## durchzuführen",
        "einen Drohnen-Schwarm ##Location## gegen seine Besitzer zu wenden"
    ],
    reasons: [
        "gegen die Megacorp", "für die Freiheit des Netzes", "um Schulden beim Syndikat zu tilgen",
        "für das nächste Upgrade", "aus Rache für den toten Partner", "um berühmt zu werden (Edgerunner)",
        "um die Wahrheit ans Licht zu bringen", "weil das System korrupt ist", "für den 'großen Score'",
        "um zu überleben", "weil der Fixer es so will", "um der Polizei zu entkommen",
        "für ein Ticket raus aus der Stadt", "um eine Krankheit zu heilen", "weil es der letzte Job ist",
        "aus purer Langeweile", "um jemanden zu beeindrucken", "weil die Stimmen es befehlen",
        "um die Welt brennen zu sehen", "für eine warme Mahlzeit", "um die eigene Akte zu löschen",
        "weil es niemand sonst tun kann", "für die Ehre der Gang", "um den Konzern zu blamieren",
        "weil die KI es berechnet hat", "um ein verlorenes Gedächtnis wiederzufinden"
    ],
    incidents: [
        "Netzwerk-Alarm ausgelöst", "Trauma-Team ist unterwegs", "Säure-Regen fällt",
        "Stromausfall im ganzen Sektor", "Ein Cyberpsycho läuft Amok", "Die Polizei riegelt das Viertel ab",
        "Eure Cyberware wird gehackt", "Eine Drohne verfolgt euch", "Werbung überflutet euer Sichtfeld",
        "Die Yakuza taucht auf", "Der Auftraggeber wurde ermordet", "Euer Fahrzeug wurde gestohlen",
        "Das Ziel ist bereits tot", "Ein Rivale taucht auf", "Das Gebäude stürzt ein",
        "Ein Erdbeben erschüttert die Stadt", "Die KI übernimmt die Kontrolle", "Ein Virus infiziert eure Systeme",
        "Die Tür ist verriegelt", "Giftgas strömt aus", "Ein Scharfschütze liegt auf der Lauer",
        "Der Schwarzmarkt wurde hochgenommen", "Eine Razzia findet statt", "Die Menge gerät in Panik",
        "Ein Stromstoß brät die Elektronik", "Die Gravitation fällt aus (lokal)", "Hologramme werden lebendig (Fehlfunktion)",
        "Die Verbindung bricht ab", "Ein Kopfgeld wurde auf euch ausgesetzt", "Der Fluchtweg ist blockiert"
    ],
    deadlines: [
        "bevor das ICE euch grillt", "bevor das Trauma-Team eintrifft", "bevor der Virus eure Gehirne schmilzt",
        "bevor die Konzern-Sichertheit da ist", "bevor der Upload fertig ist", "bis zum Morgengrauen",
        "bevor die Börse öffnet", "bevor der Akku leer ist", "in genau 5 Minuten",
        "bevor die Bombe hochgeht", "bevor das Schiff ablegt", "bevor die Beweise gelöscht sind",
        "bevor der Deal platzt", "bevor die Verstärkung eintrifft", "bevor der Sauerstoff knapp wird",
        "bevor die KI das System sperrt", "bevor der Senator die Rede hält", "sobald der Regen aufhört"
    ]
};
