
export const QUEST_DATA_FANTASY_EN = {
    givers: [
        // Nobles & officials
        { text: "The baron, who hasn't smiled since his wife died", type: "noble", gender: "m" },
        { text: "An impoverished countess in mended silk", type: "noble", gender: "f" },
        { text: "The mayor, flinching at every sound", type: "official", gender: "m" },
        { text: "A judge whose sentences are feared", type: "official", gender: "m" },
        { text: "The tax collector, always flanked by guards", type: "official", gender: "f" },
        { text: "A royal herald with a hoarse voice", type: "official", gender: "m" },
        { text: "The matron of the orphanage, stern but fair", type: "civilian", gender: "f" },
        { text: "A diplomat from the south who doesn't understand our ways", type: "official", gender: "m" },
        { text: "The jailer with the heavy keyring", type: "official", gender: "m" },
        { text: "A young noblewoman posing as a commoner", type: "noble", gender: "f" },
        { text: "A duke rumored to be bedridden", type: "noble", gender: "m" },
        { text: "The prince's old nursemaid who knows all secrets", type: "civilian", gender: "f" },
        { text: "A magistrate recently removed from office", type: "official", gender: "m" },
        { text: "The queen's handmaiden with tear-stained eyes", type: "civilian", gender: "f" },
        { text: "A scribe nervously wringing his hands", type: "scholar", gender: "m" },
        { text: "The king's taster, looking pale", type: "civilian", gender: "m" },
        { text: "A baroness with a keen interest in ruins", type: "noble", gender: "f" },
        { text: "An old chancellor pulling strings from the shadows", type: "official", gender: "m" },
        { text: "The head of the merchant guild, a woman with eyes of steel", type: "merchant", gender: "f" },
        { text: "A herald reading the proclamation with a trembling voice", type: "official", gender: "m" },
        { text: "The bailiff collecting more taxes than is due", type: "official", gender: "m" },
        { text: "An exiled princess dreaming of revenge", type: "noble", gender: "f" },
        { text: "The court jester, the only one allowed to speak the truth", type: "civilian", gender: "m" },
        { text: "An imperial envoy with sealed orders", type: "official", gender: "m" },
        { text: "The lady of the castle waiting for her husband's return", type: "noble", gender: "f" },
        { text: "A young knight knighted just yesterday", type: "noble", gender: "m" },
        { text: "The treasurer secretly embezzling gold", type: "official", gender: "m" },

        // Military & Guard
        { text: "A veteran with a deep scar across his face", type: "soldier", gender: "m" },
        { text: "The watch captain sharpening her blade", type: "soldier", gender: "f" },
        { text: "A deserter hiding in the shadows", type: "criminal", gender: "m" },
        { text: "A young recruit in oversized armor", type: "soldier", gender: "m" },
        { text: "A mercenary leader who only speaks gold", type: "soldier", gender: "m" },
        { text: "A scout smelling of rain and pine", type: "soldier", gender: "f" },
        { text: "A retired general dreaming of old battles", type: "soldier", gender: "m" },
        { text: "The castle's weapon master, a man of few words", type: "soldier", gender: "m" },
        { text: "A standard bearer who lost his company", type: "soldier", gender: "m" },
        { text: "The leader of the militia, a resolute woman", type: "soldier", gender: "f" },
        { text: "A knight in rusted armor", type: "soldier", gender: "m" },
        { text: "A marksman claiming never to miss", type: "soldier", gender: "m" },
        { text: "The quartermaster counting every copper", type: "soldier", gender: "f" },
        { text: "A captain of the guard who seems corrupt", type: "soldier", gender: "m" },
        { text: "A shieldmaiden from the frozen north", type: "soldier", gender: "f" },
        { text: "A crossbowman with a target known only to him", type: "soldier", gender: "m" },
        { text: "The fortress commander seeing enemies everywhere", type: "soldier", gender: "m" },
        { text: "A scout who has seen terrible things", type: "soldier", gender: "m" },
        { text: "The armorer selling weapons to both sides", type: "soldier", gender: "f" },
        { text: "A paladin whose faith has cracked", type: "soldier", gender: "m" },

        // Commoners & Trades
        { text: "The innkeeper of the 'Leaning Tower', a burly man", type: "civilian", gender: "m" },
        { text: "A blacksmith with hands shaped by hard work", type: "craftsman", gender: "f" },
        { text: "A peddler with a rattling cart", type: "merchant", gender: "m" },
        { text: "The gravedigger with permanently dirty boots", type: "civilian", gender: "m" },
        { text: "A beggar with surprisingly intelligent eyes", type: "civilian", gender: "m" },
        { text: "The miller complaining about strange noises", type: "civilian", gender: "f" },
        { text: "A miner looking pale and sick", type: "civilian", gender: "m" },
        { text: "The bard with a broken lute string", type: "artist", gender: "m" },
        { text: "An old woman gathering herbs in the woods", type: "civilian", gender: "f" },
        { text: "The ferryman silently holding out his hand", type: "civilian", gender: "m" },
        { text: "A stable boy dreaming of adventure", type: "civilian", gender: "m" },
        { text: "The baron's cook, known for her temper", type: "civilian", gender: "f" },
        { text: "A carpenter building many coffins lately", type: "craftsman", gender: "m" },
        { text: "An old cartographer with shaking hands", type: "scholar", gender: "m" },
        { text: "The flower girl who hears everything", type: "civilian", gender: "f" },
        { text: "A bookbinder using strange leathers", type: "craftsman", gender: "m" },
        { text: "A weaver spinning threads of fate", type: "craftsman", gender: "f" },
        { text: "The bellringer who has gone deaf", type: "civilian", gender: "m" },
        { text: "A wet nurse feeding a stranger's child", type: "civilian", gender: "f" },
        { text: "A rat catcher with a strange flute", type: "civilian", gender: "m" },

        // Shady Figures
        { text: "A figure hiding their face under a hood", type: "rogue", gender: "f" },
        { text: "The alleged leader of the local thieves", type: "rogue", gender: "m" },
        { text: "A smuggler only found at the docks", type: "rogue", gender: "f" },
        { text: "A man whose daggers are a bit too loose", type: "rogue", gender: "m" },
        { text: "The owner of a speakeasy", type: "rogue", gender: "f" },
        { text: "A fence who can get 'anything'", type: "rogue", gender: "m" },
        { text: "A burglar claiming to be retired", type: "rogue", gender: "f" },
        { text: "A forger with ink-stained fingers", type: "rogue", gender: "m" },
        { text: "A man in rags secretly giving orders", type: "rogue", gender: "m" },
        { text: "A poisoner who is very polite", type: "rogue", gender: "f" },
        { text: "A bounty hunter seeking his prey", type: "rogue", gender: "m" },
        { text: "The Beggar Queen dressed in velvet rags", type: "rogue", gender: "f" },
        { text: "A spy betraying both sides", type: "rogue", gender: "m" },
        { text: "An assassin silent as a shadow", type: "rogue", gender: "f" },
        { text: "A gambler with marked cards", type: "rogue", gender: "m" },

        // Magic & Mystery
        { text: "An alchemist with soot-stained fingers", type: "mage", gender: "m" },
        { text: "A fortune teller whose tent smells of incense", type: "mage", gender: "f" },
        { text: "The librarian of the 'Restricted Section'", type: "scholar", gender: "m" },
        { text: "A priest of a fading faith", type: "cleric", gender: "m" },
        { text: "A druid accompanied by a watchful wolf", type: "druid", gender: "f" },
        { text: "A necromancer claiming to use only 'volunteers'", type: "mage", gender: "m" },
        { text: "A hedge witch living on the swamp's edge", type: "mage", gender: "f" },
        { text: "The court wizard fearing for his influence", type: "mage", gender: "m" },
        { text: "A young warlock overwhelmed by his powers", type: "mage", gender: "m" },
        { text: "A priestess fasting and praying for days", type: "cleric", gender: "f" },
        { text: "An astrologer seeing doom in the stars", type: "scholar", gender: "m" },
        { text: "A shaman from the northern tribes", type: "druid", gender: "f" },
        { text: "A monk who broke a vow of silence", type: "cleric", gender: "m" },
        { text: "A smith hammering runes into steel", type: "mage", gender: "m" },
        { text: "A summoner arguing with unseen entities", type: "mage", gender: "f" },
        { text: "An Elementalist sparking when angry", type: "mage", gender: "m" },
        { text: "A seer with blind, milky eyes", type: "mage", gender: "f" },
        { text: "The dryad of the sacred grove", type: "druid", gender: "f" },
        { text: "An exorcist hunted by demons", type: "cleric", gender: "m" },
        { text: "An illusionist whose true face no one knows", type: "mage", gender: "f" },

        // Non-Human / Weird
        { text: "A goblin trying to pass as a halfling", type: "monster", gender: "m" },
        { text: "A dryad mourning her dying grove", type: "monster", gender: "f" },
        { text: "A ghost bound to a specific spot", type: "undead", gender: "m" },
        { text: "A talking skull that loves jokes", type: "undead", gender: "m" },
        { text: "A bear that seems unusually intelligent", type: "beast", gender: "m" },
        { text: "A vampire who hasn't bitten anyone (yet)", type: "undead", gender: "m" },
        { text: "A fae creature playing pranks", type: "monster", gender: "m" },
        { text: "A clay golem stubbornly following orders", type: "construct", gender: "m" },
        { text: "A mermaid trapped in a fountain", type: "monster", gender: "f" },
        { text: "A man who gets nervous at full moon", type: "beast", gender: "m" },
        { text: "A being made of smoke and shadow", type: "elemental", gender: "m" },
        { text: "A satyr with a pan flute", type: "monster", gender: "m" },
        { text: "A harpy with a broken wing", type: "monster", gender: "f" },
        { text: "A revenant searching for his own grave", type: "undead", gender: "m" },
        { text: "A water spirit in the shape of a horse", type: "elemental", gender: "m" }
    ],

    items: [
        // Magical
        "a long-lost amulet", "a hero's rusted sword", "a barely legible scroll",
        "a king's broken crown", "a petrified dragon egg", "a doll that moves at night",
        "an unhappy countess's wedding ring", "a potion of questionable origin", "a leather-bound book",
        "a meteorite shard", "a mad wizard's staff", "a bag of strange beans",
        "a vial of glowing liquid", "a rusty key", "a star map",
        "a dagger glowing in the dark", "an ornate but toxic chalice", "a cracked war horn",
        "a colorless cloak", "a quietly humming crystal",
        "a bone flute", "a rune-hammer", "a lantern with green light",
        "a mirror of polished obsidian", "a monster's tooth", "a white feather",
        "a mechanical heart", "a jar of ash", "a coin with two heads",
        "a compass spinning wildly", "a bottle of rainwater", "a trapped wisp",
        "a mask with no eyeholes", "ivory chess pieces", "a ring with a ruby",
        "an hourglass running backwards", "a die that always rolls six", "a map that changes",
        "a stone that feels warm", "a necklace of wolf teeth", "a book with empty pages",
        "a chalice that is never empty", "a bell that makes no sound", "a metal gauntlet",
        "spectacles revealing the invisible", "a boot that never gets dirty", "a quill writing by itself",
        "a seed glowing in the dark", "a vial of dragon tears", "a dagger of ice",

        // Mundane / Valuable
        "a heavy sack of gold", "fortress blueprints", "an incriminating letter",
        "a wanted criminal's head", "a crate of contraband", "a cask of ancient wine",
        "the inn's deed", "a bundle of rare furs", "collected taxes",
        "an embarrassing poem", "a captain's logbook", "a list of names",
        "the baron's signet", "a shipment of exotic spices", "a masterfully forged sword",
        "the wine cellar key", "a stolen painting", "a tiara",
        "a last will", "bank sketches", "a crate of tropical fruit",
        "a rare lute", "siege weapon plans", "a collection of pinned insects",
        "a secret beer recipe", "a silk dress", "a pouch of gems",
        "a land deed", "a chest of silver cutlery", "a rare spice from the east",
        "bridge construction plans", "a pouch of rare coins", "a barrel of finest tobacco",
        "a statue of pure gold", "a carpet from the faraway south", "a collection of rare wines",
        "a book on herbalism", "a brass sextant", "a crate of porcelain",
        "a cage with exotic birds", "an old legion's banner", "a pouch of pearls",

        // Organic / Weird
        "a witch's heart", "a dragon tooth", "three griffin feathers",
        "a rare nightbloom", "a saint's ashes", "a jar of eyes in alcohol",
        "a thief's mummified hand", "a screaming mandrake", "spider venom glands",
        "iridescent scales", "white antlers", "a vial of vampire blood",
        "a frozen tear", "a ghost's breath", "a shimmering stone",
        "a traitor's tongue", "a golden egg", "moss from an ancient grave",
        "a human-shaped root", "a shard of ice",
        "a knucklebone", "a lock of golden hair", "a piece of petrified skin",
        "a vial of shadow", "a beetle shining like a gem", "a pulsating mushroom",
        "wood from a gallows tree", "a stone from a giant's stomach", "a piece of unicorn horn",
        "a phoenix feather", "a leviathan scale", "a drop of angel blood",
        "bark from the world tree", "a werewolf tooth", "a harpy claw"
    ],

    locations_dungeon: [
        "from the crypt", "in the damp cellar", "in overgrown ruins",
        "in the spider nest", "in the stinking sewers", "in the abandoned shaft",
        "in the dungeon", "in the old torture chamber", "in the maze below the city",
        "in the catacombs", "in the bear cave", "in the hideout",
        "in the king's tomb", "in the depths", "in the lair",
        "in the sunken library", "in the volcano's heart", "in the ice cave",
        "in the serpent temple", "in the hall of echoes",
        "in the Grotto of the Forgotten", "in the Shaft of Despair", "in the Lion's Den",
        "in the underground lake", "in the Chamber of Trials", "in the Rat Tunnel",
    ],

    locations_urban: [
        "from the treasury", "in the secret library wing", "in the deserted square",
        "in the wizard's tower", "in the bedchamber", "in the sooty smithy",
        "in the temple", "in the barracks", "in the harbor warehouse",
        "in the throne room", "in the kitchen", "in the bell tower", "in the orphanage",
        "in the opera", "in the bathhouse", "in the academy", "in the prison tower",
        "in the manor", "in the trading post", "in the dilapidated villa",
        "on the cathedral roof", "in the lab", "in the crypt",
        "in the city archives", "in the guildhall", "in the gate watchtower",
        "in the mill by the river", "in the coaching inn", "in the brewery",
        "in the hospital", "in the theater", "in the circus tent",
        "in the bakery", "in the clock tower", "in the observatory",
    ],

    locations_wild: [
        "in the orc camp", "at the shipwreck", "in the misty swamp",
        "on the mountain peak", "in the deep woods", "by the old stone bridge",
        "in the druid circle", "at the spring", "in the burnt village",
        "in the oasis", "in the valley", "in the graveyard",
        "at the crater lake", "in the petrified forest", "on the island",
        "on the cliff", "on the battlefield", "by the waterfall",
        "in the gorge", "on the pass",
        "on the lake shore", "in the thorn thicket", "in the clearing",
        "at the crossroads", "in the Valley of Mists", "on the plateau",
        "in the Wisp Swamp", "on the Coast of Bones", "in the Forest of Whispering Trees",
    ],

    locations_mystic: [
        "in the shadow world", "in a dream", "in the flying fortress",
        "in a giant fish's belly", "on an ice floe", "in the house without doors",
        "on the moon", "in the mirror world", "in an hourglass",
        "on a turtle's back", "in the clouds", "in the fey realm",
        "in the Labyrinth of Time", "in the City of the Dead", "in the Crystal Palace",
        "in the Eye of the Storm", "inside a volcano", "on a comet",
        "in the Realm of Giants", "in the Underworld", "in Limbo"
    ],

    locations_general: [
        { text: "in the Whispering Woods" },
        { text: "in the ruins of Dragonkeep" },
        { text: "in the misty moors" },
        { text: "in the alleys of the undercity" },
        { text: "at the cliffs" },
        { text: "in the desert" },
        { text: "on the floating islands" },
        { text: "in the Valley of Kings" },
        { text: "in the cursed city" },
        { text: "at the world's end" },
        { text: "in the realm of the dead" },
        { text: "in the glass city" },
        { text: "in the deep jungle" },
        { text: "on the frozen sea" },
        { text: "in the Realm of Shadow" },
        { text: "on the Isle of the Banished" },
        { text: "in the Forbidden Valley" },
        { text: "in the City of a Thousand Towers" },
        { text: "in the Land of Eternal Ice" },
        { text: "in the Jungle of Beasts" }
    ],

    targets_person: [
        "the lost prince", "the sequestered daughter", "a key witness",
        "the bandit captain", "a rogue mage", "the baron's ghost",
        "pilgrims", "the last heir", "a cursed knight",
        "the high priestess", "a spy", "a merchant", "the elder",
        "the miller", "a doppelganger", "the rebel leader", "a witch",
        "a cultist", "a paladin", "an oracle", "a ghost child",
        "a summoner", "an inventor", "a traveler", "the guardian",
        "the executioner", "a prophet", "a hermit", "a gladiator",
        "a smith", "an alchemist", "a bard", "a druid", "a necromancer"
    ],

    targets_monster: [
        "a wild bear", "a unicorn", "a golem", "a vampire",
        "a dragon", "a fallen angel", "a nymph", "the rat king",
        "a forest spirit", "a shapeshifter", "a siren", "a werewolf",
        "a lich", "a demon", "an archangel", "a time traveler",
        "a shadow", "a baby tarrasque", "a hydra", "a griffin",
        "a manticore", "a basilisk", "a giant spider", "a beholder"
    ],

    actions_item: [
        "to retrieve", "to find", "to steal", "to destroy", "to investigate",
        "to acquisition", "to hide", "to repair", "to protect", "to translate",
        "to decode", "to copy", "to curse", "to sacrifice", "to bless",
        "to seal", "to smuggle", "to forge", "to bury", "to burn",
        "to catalogue", "to appraise", "to enchant", "to cleanse",
        "to shatter", "to activate", "to deform", "to trade", "to gift"
    ],

    actions_person: [
        "to find", "to protect", "to free", "to escort", "to kill",
        "to question", "to convince", "to bribe", "to heal", "to awaken",
        "to bury", "to deceive", "to seduce", "to capture", "to save",
        "to warn", "to shadow", "to interrogate", "to convert", "to kidnap",
        "to blackmail", "to marry", "to mock", "to rob", "to denounce",
        "to teach", "to avenge", "to pardon", "to condemn"
    ],

    actions_monster: [
        "to hunt", "to kill", "to banish", "to catch", "to study",
        "to appease", "to summon", "to bind", "to observe", "to track",
        "to tame", "to feed", "to skin", "to sketch", "to stun",
        "to drive away", "to control", "to trick", "to avoid",
        "to lure into a trap", "to redeem"
    ],

    task_templates: [
        // --- Item Quests ---
        "##Item## ##Location## ##ActionItem##",
        "to steal ##Item## and hide it ##Location##",
        "to deliver ##Item## ##Location##",
        "to find ##Item## ##Location## and ##ActionItem## it",
        "to ##ActionItem## ##Item## from a thief ##Location##",
        "to save ##Item## ##Location## from destruction",
        "to defend ##Item## ##Location## from rivals",
        "to secretly place ##Item## ##Location##",
        "to examine ##Item## ##Location## and then ##ActionItem## it",
        "to collect fragments of ##Item## ##Location##",
        "to verify the authenticity of ##Item## ##Location##",

        // --- Person Quests ---
        "##TargetPerson## ##Location## ##ActionPerson##",
        "to find ##TargetPerson## and ##ActionPerson## them",
        "to safely escort ##TargetPerson## ##Location##",
        "to protect ##TargetPerson## ##Location## from an assassination",
        "to deliver a message to ##TargetPerson## ##Location##",
        "to shadow ##TargetPerson## ##Location## and report back",
        "to confront ##TargetPerson## ##Location##",
        "to help ##TargetPerson## escape ##Location##",
        "to find a burial site for ##TargetPerson## ##Location##",
        "to clear ##TargetPerson##'s name ##Location##",
        "to free ##TargetPerson## ##Location## from captivity",
        "to heal ##TargetPerson## ##Location##",
        "to teach ##TargetPerson## ##Location##",
        "to train ##TargetPerson## ##Location##",
        "to comfort ##TargetPerson## ##Location##",
        "to make ##TargetPerson## ##Location## laugh",
        "to seduce (or matchmake) ##TargetPerson## ##Location##",
        "to insult ##TargetPerson## ##Location## (for a duel)",
        "to ignore ##TargetPerson## ##Location## (as a test)",
        "to pickpocket ##TargetPerson## ##Location## (just a trifle)",
        "to eavesdrop on ##TargetPerson## ##Location##",
        "to follow ##TargetPerson## ##Location##",
        "to draw ##TargetPerson## ##Location## (portrait)",
        "to sing about ##TargetPerson## ##Location##",
        "to curse ##TargetPerson## ##Location## (lightly)",
        "to bless ##TargetPerson## ##Location##",
        "to shave ##TargetPerson## ##Location## (the barber is sick)",
        "to disguise ##TargetPerson## ##Location##",
        "to feed ##TargetPerson## ##Location## (famine)",
        "to save ##TargetPerson## ##Location## (from themselves)",
        "to find ##TargetPerson## ##Location## (hide and seek)",
        "to catch ##TargetPerson## ##Location## (race)",
        "to defeat ##TargetPerson## ##Location## (arm wrestling)",
        "to persuade ##TargetPerson## ##Location##",
        "to bribe ##TargetPerson## ##Location##",
        "to threaten ##TargetPerson## ##Location##",
        "to warn ##TargetPerson## ##Location##",
        "to inform ##TargetPerson## ##Location##",
        "to question ##TargetPerson## ##Location##",
        "to examine ##TargetPerson## ##Location## (doctor)",
        "to bury ##TargetPerson## ##Location## (dignified)",
        "to resurrect ##TargetPerson## ##Location## (necromancy?)",
        "to summon ##TargetPerson## ##Location## (ghost?)",
        "to banish ##TargetPerson## ##Location##",
        "to forget ##TargetPerson## ##Location##",
        "to remember ##TargetPerson## ##Location##",
        "to forgive ##TargetPerson## ##Location##",
        "to thank ##TargetPerson## ##Location##",
        "to hate ##TargetPerson## ##Location##",
        "to love ##TargetPerson## ##Location##",
        "to fear ##TargetPerson## ##Location##",
        "to respect ##TargetPerson## ##Location##",
        "to lead ##TargetPerson## ##Location##",
        "to follow ##TargetPerson## ##Location##",
        "to serve ##TargetPerson## ##Location##",

        // --- Monster Quests ---
        "##TargetMonster## ##Location## ##ActionMonster##",
        "to track down ##TargetMonster## and ##ActionMonster## it",
        "to repel an attack by ##TargetMonster## ##Location##",
        "to drive ##TargetMonster## ##Location## out of its nest",
        "to find clues about ##TargetMonster## ##Location##",
        "to lure ##TargetMonster## ##Location## into a trap",
        "to retrieve loot stolen by ##TargetMonster## ##Location##",
        "to capture ##TargetMonster## ##Location## alive",
        "to gain ##TargetMonster## ##Location## as an ally",
        "to study ##TargetMonster## ##Location## without being seen",
        "to free ##TargetMonster## ##Location## from a curse",
        "to feed ##TargetMonster## ##Location## (it is hungry)",
        "to heal ##TargetMonster## ##Location## (it is injured)",
        "to wash ##TargetMonster## ##Location## (it smells)",
        "to train ##TargetMonster## ##Location## (as a guardian)",
        "to ride ##TargetMonster## ##Location## (rodeo)",
        "to milk ##TargetMonster## ##Location## (for poison/antidote)",
        "to shear ##TargetMonster## ##Location## (for wool/scales)",
        "to paint ##TargetMonster## ##Location## (from a safe distance)",
        "to sing to ##TargetMonster## ##Location## (lullaby)",
        "to insult ##TargetMonster## ##Location## (to distract it)",
        "to steal from ##TargetMonster## ##Location## (a tooth?)",
        "to summon ##TargetMonster## ##Location##",
        "to banish ##TargetMonster## ##Location##",
        "to hunt ##TargetMonster## ##Location##",
        "to skin ##TargetMonster## ##Location##",
        "to cook ##TargetMonster## ##Location## (or cook for it)",
        "to dissect ##TargetMonster## ##Location## (scientifically)",
        "to interview ##TargetMonster## ##Location## (does it speak?)",
        "to seduce ##TargetMonster## ##Location## (Bards...)",
        "to trick ##TargetMonster## ##Location##",
        "to scare ##TargetMonster## ##Location##",
        "to surprise ##TargetMonster## ##Location##",
        "to watch ##TargetMonster## ##Location##",
        "to follow ##TargetMonster## ##Location##",
        "to catch ##TargetMonster## ##Location##",
        "to release ##TargetMonster## ##Location##",
        "to protect ##TargetMonster## ##Location## (from poachers)",
        "to hide ##TargetMonster## ##Location##",
        "to sell ##TargetMonster## ##Location##",
        "to buy ##TargetMonster## ##Location##",
        "to trade ##TargetMonster## ##Location##",
        "to breed ##TargetMonster## ##Location##",
        "to hatch ##TargetMonster## ##Location## (egg)",
        "to bury ##TargetMonster## ##Location##",
        "to resurrect ##TargetMonster## ##Location##",
        "to fear ##TargetMonster## ##Location##",
        "to respect ##TargetMonster## ##Location##",
        "to imitate ##TargetMonster## ##Location##",
        "to understand ##TargetMonster## ##Location##",

        // --- Narrative & Complex Quests ---
        "to convince ##TargetPerson## to give up ##Item##",
        "to kill ##TargetMonster## to obtain ##Item##",
        "to use ##Item## to distract ##TargetMonster## ##Location##",
        "to sacrifice ##Item## ##Location## to appease ##TargetMonster##",
        "to find out who stole ##Item## ##Location##",
        "to disguise as a guard to free ##TargetPerson## ##Location##",
        "to monitor ##TargetPerson## ##Location## at a secret meeting",
        "to uncover dark secrets about ##TargetPerson## ##Location##",
        "to win a contest against ##TargetPerson## ##Location##",
        "to discover the origin of ##Item## ##Location##",
        "to ensure ##Item## ##Location## is never found",
        "to perform a ritual ##Location## to banish ##TargetMonster##",
        "to protect ##TargetPerson## ##Location## from an angry mob",
        "to get ##TargetPerson## ##Location## to trust you",
        "to cause unrest ##Location## to lure out ##TargetPerson##",
        "to spread rumors about ##TargetMonster## ##Location## to avoid panic",
        "to rehabilitate ##TargetPerson## ##Location## using ##Item##",
        "to defend ##TargetPerson## ##Location## before a court",
        "to negotiate a peace treaty for ##TargetPerson## ##Location##",
        "to check ##Item## ##Location## for authenticity",
        "to sell ##Item## on the black market ##Location##",
        "to protect ##Item## ##Location## from a thief",
        "to make a duplicate of ##Item## ##Location##",
        "to win ##Item## ##Location## in a poker game",
        "to save ##Item## ##Location## from a burning house",
        "to recover ##Item## ##Location## from a frozen lake",
        "to disguise the magical aura of ##Item## ##Location##",
        "to bless ##Item## ##Location##",
        "to curse ##Item## ##Location## (for a client)",
        "to break ##Item## ##Location## to break its power",
        "to reassemble parts of ##Item## ##Location##",
        "to use ##Item## ##Location## as bait",
        "to defend ##Item## ##Location## against a false claim",
        "to find out the true name of ##Item## ##Location##",
        "to return ##Item## ##Location## to a ghost",
        "to bury ##Item## ##Location## and draw a map",
        "to polish ##Item## ##Location## until it shines (magically?)",
        "to protect ##Item## ##Location## from rust",
        "to identify ##Item## ##Location##",
        "to steal ##Item## ##Location## from a dragon's hoard",
        "to give ##Item## ##Location## to a beggar",
        "to throw ##Item## ##Location## into a volcano",
        "to harden ##Item## ##Location## with dragon's blood",
        "to sing to ##Item## ##Location## to activate it",
        "to protect ##Item## ##Location## from sunlight",
        "to use ##Item## ##Location## only during a full moon",
        "to engrave ##Item## ##Location## with runes",
        "to dip ##Item## ##Location## in wine",
        "to weigh ##Item## ##Location## (it is lighter than it should be)",
        "to shape ##Item## ##Location## into a golem",
        "to use ##Item## ##Location## as a key",
        "to auction ##Item## ##Location##",
        "to eat ##Item## ##Location## (is it edible?)",
        "to plant ##Item## ##Location## (does it grow?)",
        "to forge ##Item## ##Location##",
        "to melt ##Item## ##Location##",
        "to worship ##Item## ##Location##",
        "to fear ##Item## ##Location##",
        "to hunt ##Item## ##Location## (does it move?)",
        "to question ##Item## ##Location## (does it speak?)",
        "to marry ##Item## ##Location## (a strange cult?)",
        "to free ##Item## ##Location## (is a soul inside?)",
        "to catch ##Item## ##Location##",
        "to tame ##Item## ##Location## (it is wild)",
        "to ride ##Item## ##Location## (it is large)",
        "to read ##Item## ##Location##",
        "to understand ##Item## ##Location##",
        "to forget ##Item## ##Location##",
        "to use ##Item## ##Location## to activate an ancient mechanism",
        "to support ##TargetPerson## ##Location## in claiming a lost heritage",
        "to convict ##TargetPerson## ##Location## of corruption",
        "to contain a plague ##Location## by finding ##Item##",
        "to stop ##TargetPerson## ##Location## from making a terrible mistake",
        "to break a curse tormenting ##TargetPerson## ##Location## using ##Item##",
        "to test ##TargetPerson## ##Location##",
        "to smuggle ##Item## ##Location## without being noticed by guards",
        "to incite a rebellion ##Location## to overthrow ##TargetPerson##",
        "to feed ##TargetMonster## ##Location## so it doesn't attack the city",
        "to forge an alliance between ##TargetPerson## and ##TargetMonster## ##Location##",
        "to find out that ##Item## actually belongs to ##TargetPerson## ##Location##",
        "to rewrite the history of ##Item## ##Location##",
        "to fulfill the prophecy about ##TargetPerson## ##Location##",
        "to break the curse of ##Location## by destroying ##Item##",
        "to convince ##TargetPerson## ##Location## to become King",
        "to end the war between ##TargetMonster## and the humans ##Location##",
        "to cleanse the source of magic ##Location##",
        "to seal the portal to the underworld ##Location## with ##Item##",
        "to find the lost city ##Location## and recover ##Item##",
        "to wake the dragon ##Location## to save the world",
        "to appease the gods ##Location## by sacrificing ##Item##",
        "to change the fate of ##TargetPerson## ##Location##",
        "to turn back time ##Location## to save ##TargetPerson##",
        "to find out the true name of the demon ##Location##",
        "to save the soul of ##TargetPerson## ##Location## from hell",
        "to heal the spirit of the forest ##Location##",
        "to rearrange the stars ##Location##",
        "to make the moon ##Location## shine again",
        "to win the heart of ##TargetPerson## ##Location##",
        "to repair the mind of ##TargetPerson## ##Location##",
        "to restore the memories of ##TargetPerson## ##Location##",
        "to enact a new law ##Location## that protects ##TargetPerson##",
        "to found a school for magic ##Location##",
        "to build an orphanage ##Location##",
        "to save a library ##Location## from fire",
        "to organize a feast for ##TargetMonster## ##Location##",
        "to perform a play about ##TargetPerson## ##Location##",
        "to compose a song about ##Item## ##Location##",
        "to expose ##TargetPerson## ##Location##",
        "to translate a lost manuscript ##Location## to understand ##TargetMonster##",
        "to challenge ##TargetPerson## ##Location## to a duel to win ##Item##",
        "to redeem the ghost haunting ##TargetPerson## ##Location##",
        "to ambush the thieves who stole ##Item## ##Location##",
        "to protect ##TargetPerson## ##Location## at the wedding from sabotage",
        "to refute a rumor ##Location## that is ruining ##TargetPerson##",
        "to tame ##TargetMonster## ##Location## and use it as a mount",
        "to prepare an ambush for ##TargetMonster## ##Location##",
        "to set a trap for ##TargetPerson## ##Location##",
        "to prove that ##TargetMonster## ##Location## is just a myth",


        // --- Social / Intrigue ---
        "to spread a false rumor about ##TargetPerson## ##Location##",
        "to disguise as a servant to spy on ##TargetPerson## ##Location##",
        "to smuggle a love letter to ##TargetPerson## ##Location##",
        "to eavesdrop on ##TargetPerson## ##Location## during a secret meeting",
        "to ruin the reputation of ##TargetPerson## ##Location##",
        "to spin a web of intrigue against ##TargetPerson## ##Location##",
        "to trick ##TargetPerson## ##Location## into revealing a secret",
        "to provoke a diplomatic incident ##Location##",
        "to prevent (or arrange) a forced marriage of ##TargetPerson## ##Location##",
        "to bribe a guard ##Location## to look the other way",
        "to blend in at a banquet ##Location## while stealing something",
        "to forge a title of nobility for ##TargetPerson## ##Location##",
        "to hide a secret message in a song ##Location##",
        "to drink ##TargetPerson## under the table at a feast ##Location##",
        "to settle (or fuel) a feud between two noble houses ##Location##",
        "to insult the King/Duke ##Location## through a play",
        "to find a will ##Location## and 'correct' it",
        "to uncover a scandal about ##TargetPerson## ##Location##",
        "to infiltrate a secret society ##Location##",
        "to negotiate peace between ##TargetMonster## and the village ##Location##",
        "to start a petition ##Location## to oust the sheriff",
        "to warn ##TargetPerson## ##Location## of an assassination attempt (anonymously)",
        "to expose a doppelganger of ##TargetPerson## ##Location##",
        "to cover up a forbidden romance ##Location##",
        "to bribe a bard ##Location## to sing a specific song",
        "to act as a lawyer at a trial ##Location## (without a license)",
        "to sabotage a trade agreement ##Location##",
        "to maintain perfect court etiquette ##Location## to impress someone",
        "to ridicule a rival ##Location##",
        "to uncover a conspiracy against the throne ##Location##",
        "to convince someone ##Location## that a monster is harmless",
        "to deliver a blackmail letter to ##TargetPerson## ##Location##",
        "to test the loyalty of the guards ##Location##",
        "to mediate a dispute between merchants ##Location##",
        "to impersonate ##TargetPerson## ##Location## to incur debts",
        "to steal an invitation to the royal ball ##Location##",
        "to make the court jester ##Location## cry",
        "to make a bet on the fate of ##TargetPerson## ##Location##",
        "to read the princess's diary ##Location## (and put it back)",
        "to persuade a ghost ##Location## to stop haunting",
        "to incite the crowd ##Location## to riot",
        "to put a noble knight ##Location## in a compromising situation",
        "to bribe the cook ##Location## to oversalt the food",
        "to convey a secret sign to ##TargetPerson## ##Location##",
        "to distract the master of ceremonies ##Location##",
        "to give a speech ##Location## that no one forgets",
        "to secretly pay off ##TargetPerson##'s debts ##Location##",
        "to win a duel of words with ##TargetPerson## ##Location##",
        "to gain the trust of a street urchin ##Location##",
        "to invent a legend about ##TargetMonster## ##Location##",


        // --- Reverse / Morally Grey ---
        "to plant evidence ##Location## to incriminate ##TargetPerson##",
        "to help ##TargetMonster## ##Location## ambush its hunters",
        "to steal the donation for the orphanage ##Location##",
        "to blackmail ##TargetPerson## ##Location##",
        "to commit a theft ##Location## and make it look like an accident",
        "to hide a cursed object ##Location## to cause chaos",
        "to betray ##TargetPerson## ##Location## to their enemies",
        "to ambush a prisoner transport ##Location##",
        "to contaminate the holy water in the temple ##Location##",
        "to ignore (or participate in) a slave trade ##Location##",
        "to sell contraband ##Location## to the guards",
        "to summon a demon ##Location## (accidentally?)",
        "to set fire to the harvest ##Location##",
        "to sabotage a bridge ##Location## before the King passes",
        "to mix poison into ##TargetPerson##'s cup ##Location##",
        "to swap a valuable artifact ##Location## for a fake",
        "to disturb the peace of the dead ##Location## to steal a ring",
        "to frame an innocent beggar ##Location## as a scapegoat",
        "to open the city gates ##Location## for the Orcs",
        "to burn a holy book ##Location##",
        "to tell a lie to the Inquisitor ##Location##",
        "to supply a fence ##Location## with stolen goods",
        "to set the dogs on ##TargetPerson## ##Location##",
        "to keep an escape route open for the murderer ##Location##",
        "to forge the King's seal ##Location##",
        "to extort protection money from merchants ##Location##",
        "to make the corpse of ##TargetPerson## ##Location## 'disappear'",
        "to hide a poacher ##Location## from the ranger",
        "to destroy the antidote ##Location##",
        "to ring the bells ##Location## at the wrong time to cause panic",
        "to build a trap for the adventuring party ##Location##",
        "not to betray the master thief ##Location##",
        "to help oneself to the supplies of a starving family ##Location##",
        "to feed a monster ##Location## to make it stronger",
        "to steal the key to the dungeon ##Location##",
        "to get the guards ##Location## drunk with tainted wine",
        "to forge a map that leads ##TargetPerson## ##Location## to their death",
        "to bribe the oracle ##Location## to give a false prophecy",
        "to supply a necromancer ##Location## with body parts",
        "to extinguish the last torch ##Location##",
        "to manipulate the sailors' compass ##Location##",
        "to cut a rope holding ##Item## ##Location##",
        "to cast a sleep spell on the guardian ##Location##",
        "to grant entry to a vampire ##Location##",
        "to swap the healing potion ##Location## with poison",
        "to intimidate the only witness ##Location##",
        "to keep the ransom for ##TargetPerson## ##Location## for oneself",
        "to release a werewolf ##Location## during a full moon",
        "to replace the crown jewels ##Location## with glass stones",


        // --- Detective / Mystery ---
        "to find out why ##TargetPerson## secretly visits ##Location## every night",
        "to unmask the spy among the guards ##Location##",
        "to investigate the crime scene ##Location## and secure evidence",
        "to verify the alibi of ##TargetPerson## ##Location##",
        "to discover who wrote the letter to ##TargetPerson## ##Location##",
        "to reveal the true identity of ##TargetPerson## ##Location##",
        "to solve a cryptic puzzle ##Location## that protects ##Item##",
        "to find the source of a strange noise ##Location##",
        "to track down the missing children ##Location##",
        "to find out who poisoned the water in the well ##Location##",
        "to identify the King's killer ##Location##",
        "to translate an ancient symbol ##Location##",
        "to find the secret entrance to the library ##Location##",
        "to trace the bloodline of ##TargetPerson## ##Location##",
        "to figure out which of the three chests ##Location## contains the trap",
        "to find the owner of a lost amulet ##Location##",
        "to draw a sketch of the thief ##Location##",
        "to read the footprints in the mud ##Location##",
        "to find out why the animals ##Location## are acting crazy",
        "to reveal an invisible message on ##Item## ##Location##",
        "to question the witness ##Location## before they disappear",
        "to determine the motive for the raid ##Location##",
        "to examine an alchemy lab ##Location## for residues",
        "to find out who stole the dragon eggs ##Location##",
        "to ask the ghost of the deceased ##Location## for their killer",
        "to map a labyrinth ##Location##",
        "to crack the code for the treasury ##Location##",
        "to distinguish a fake from an original ##Location##",
        "to find out who is blackmailing ##TargetPerson## ##Location##",
        "to locate the rebel hideout ##Location##",
        "to analyze the ingredients of an unknown potion ##Location##",
        "to find out why the bells ##Location## are ringing by themselves",
        "to find the saboteur on the ship ##Location##",
        "to interpret the meaning of the star constellation ##Location##",
        "to find out who the father of the bastard ##Location## is",
        "to determine the origin of a meteor ##Location##",
        "to reconstruct the assassin's escape route ##Location##",
        "to open a sealed will ##Location## without breaking the seal",
        "to find out which painting ##Location## opens the secret passage",
        "to find the lie in ##TargetPerson##'s statement ##Location##",
        "to convict the traitor in the council ##Location##",
        "to find out where the secret passage ##Location## ends",
        "to recognize the pattern of attacks ##Location##",
        "to decipher a diary ##Location##",
        "to determine the true owner of ##Item## ##Location##",
        "to find out why magic ##Location## isn't working",
        "to expose the doppelganger ##Location##",
        "to sift through the ashes ##Location## for clues",
        "to eavesdrop on a conversation through the wall ##Location##",
        "to identify the dead man's tattoo ##Location##",


        // --- Fantasy Specific (Rituals & Magic) ---
        "to perform a magical ritual ##Location## to influence the weather",
        "to break a curse on ##Item## ##Location##",
        "to telepathically bond with ##TargetMonster## ##Location##",
        "to decipher the ancient runes ##Location##",
        "to make a pact with a spirit ##Location##",
        "to close a portal to another world ##Location##",
        "to charge ##Item## ##Location## with magical energy",
        "to draw a protective circle ##Location## to save ##TargetPerson##",
        "to hatch a dragon egg ##Location##",
        "to bring a golem ##Location## to life",
        "to decipher the true meaning of a prophecy ##Location##",
        "to make a pact with a Fey creature ##Location## (carefully)",
        "to pull a sword from a stone ##Location##",
        "to revive a petrified adventurer ##Location##",
        "to discover the name of a demon ##Location## to banish it",
        "to win a bard's tournament ##Location##",
        "to brew a potion ##Location## that grants immortality",
        "to create a homunculus ##Location##",
        "to realign the ley lines ##Location##",
        "to bind an elemental ##Location##",
        "to undertake an astral journey ##Location##",
        "to enter the dreams of ##TargetPerson## ##Location##",
        "to step through a mirror ##Location##",
        "to speak with animals ##Location##",
        "to shapeshift into an animal ##Location##",
        "to catch lightning ##Location## in a bottle",
        "to climb a rainbow ##Location##",
        "to catch a shadow ##Location##",
        "to preserve the echo of a scream ##Location##",
        "to stop time ##Location## for an hour",
        "to become invisible ##Location##",
        "to walk through walls ##Location##",
        "to read minds ##Location##",
        "to practice telekinesis ##Location##",
        "to throw a fireball ##Location## (target practice)",
        "to weave a protective spell ##Location##",
        "to see through an illusion spell ##Location##",
        "to reverse a transformation spell ##Location##",
        "to mix a love potion ##Location##",
        "to administer a truth potion ##Location##",
        "to drink a forgetting potion ##Location##",
        "to test a flight potion ##Location##",
        "to brew a strength potion ##Location##",
        "to improve a healing potion ##Location##",
        "to neutralize a poison potion ##Location##",
        "to find a luck potion ##Location##",
        "to destroy a bad luck potion ##Location##",
        "to seek a rejuvenation potion ##Location##",
        "to guard a wisdom potion ##Location##",
        "to distribute a courage potion ##Location##"
    ],

    reasons: [
        { text: "to settle a debt" },
        { text: "to save family honor" },
        { text: "to pay a ransom" },
        { text: "to avenge a father's death" },
        { text: "to get rich" },
        { text: "to gain influence" },
        { text: "to save the village" },
        { text: "to stop a sickness" },
        { text: "to fulfill a pact" },
        { text: "to win a bet" },
        { text: "to beat a rival" },
        { text: "to appease the gods" },
        { text: "to break a curse" },
        { text: "to impress someone" },
        { text: "to keep a secret" },
        { text: "to join a guild" },
        { text: "to recover memories" },
        { text: "to avoid marriage" },
        { text: "to cover tracks" },
        { text: "to cause chaos" },
        { text: "out of boredom" },
        { text: "due to a prophecy" },
        { text: "due to blackmail" },
        { text: "because of a dream" },
        { text: "to find peace" },
        { text: "to live forever" },
        { text: "to fix a mistake" },
        { text: "to create something" },
        { text: "to seize power" },
        { text: "to bring hope" },
        { text: "to pay debts" },
        { text: "to escape" },
        { text: "to find the truth" },
        { text: "for a perfect meal" },
        { text: "to save the world" },
        { text: "to prevent a war" },
        { text: "to break a spell" },
        { text: "to find a treasure" },
        { text: "to save a friend" },
        { text: "to destroy an enemy" },
        { text: "to find love" },
        { text: "to keep sanity" },
        { text: "to restore order" },
        { text: "to maintain balance" },
        { text: "to kill a god" }
    ],

    incidents: [
        { text: "A comet has been trailing red across the sky for nights" },
        { text: "Graves in the old churchyard lie open" },
        { text: "Thick fog hasn't lifted for days" },
        { text: "Last night, all mirrors cracked" },
        { text: "A messenger collapsed dead at the gates, note in hand" },
        { text: "Bloody tears run down the temple statue's face" },
        { text: "The river tastes of iron and runs dark" },
        { text: "Sometimes the air shimmers, like a heat haze" },
        { text: "A child was born speaking" },
        { text: "The town clock struck thirteen" },
        { text: "Barn supplies rotted overnight" },
        { text: "No fire warms, no matter how high it's stoked" },
        { text: "A shadow as big as a dragon glided over roofs" },
        { text: "Dead birds litter the streets" },
        { text: "An unmanned ship drifted into harbor" },
        { text: "After the quake, a hole gapes in the market" },
        { text: "Animals are restless and aggressive" },
        { text: "People vanish since the circus arrived" },
        { text: "Strange lights glow in the woods at night" },
        { text: "Town cats all stare in one direction" },
        { text: "A storm rages, but no rain falls" },
        { text: "Shadows move on their own" },
        { text: "A madman screams old verses" },
        { text: "Voices come from the well" },
        { text: "Trees lost leaves overnight" },
        { text: "Everyone had the same dream" },
        { text: "Gold coins appear where none should be" },
        { text: "A dense flock of ravens circles the tower" },
        { text: "Milk sours as soon as it's milked" },
        { text: "An earthquake revealed old ruins" },
        { text: "The stars are in a wrong constellation" },
        { text: "A stranger is in town asking odd questions" },
        { text: "Wells are yielding salt water" },
        { text: "Town children sing an unknown song" },
        { text: "A wolf howls in broad daylight" },
        { text: "Bells ring by themselves" },
        { text: "A fog smelling of sulfur rolls in" },
        { text: "Crops withered overnight" },
        { text: "It rained fish over the city" },
        { text: "Candles burn with a green flame" }
    ],

    deadlines: [
        { text: "before the candle dies" },
        { text: "until midnight strikes" },
        { text: "before the blood moon peaks" },
        { text: "in three days" },
        { text: "before the guard arrives" },
        { text: "immediately" },
        { text: "before winter" },
        { text: "before the effect fades" },
        { text: "before the portal closes" },
        { text: "until dawn" },
        { text: "before it wakes" },
        { text: "before the tide" },
        { text: "before time runs out" },
        { text: "before the king dies" },
        { text: "before the last grain of sand falls" },
        { text: "before the sun sets" },
        { text: "before the storm breaks" },
        { text: "before the ceremony begins" }
    ]
};
