
export const QUEST_DATA_PIRATE_DE = {
    givers: [
        { text: "Ein Piratenkapitän mit einem hölzernen Bein", type: "rogue", gender: "m" },
        { text: "Eine verrufene Freibeuterin", type: "rogue", gender: "f" },
        { text: "Der Quartiermeister, der die Karten hütet", type: "rogue", gender: "m" },
        { text: "Ein alter Seebär, der von Monstern faselt", type: "civilian", gender: "m" },
        { text: "Eine Sirene, die an Land gekommen ist", type: "monster", gender: "f" },
        { text: "Der Gouverneur der Inselkolonie", type: "official", gender: "m" },
        { text: "Ein Schiffszimmermann mit goldenen Zähnen", type: "craftsman", gender: "m" },
        { text: "Eine Wahrsagerin aus dem Voodoo-Viertel", type: "mage", gender: "f" },
        { text: "Ein Papagei, der Geheimnisse plappert", type: "beast", gender: "m" },
        { text: "Der Geist eines ertrunkenen Admirals", type: "undead", gender: "m" },
        { text: "Ein Schiffskoch, dessen Eintopf tödlich ist", type: "civilian", gender: "m" },
        { text: "Eine Gestalt in nassem Seegras", type: "monster", gender: "f" },
        { text: "Der Hafenmeister, der bestechlich ist", type: "official", gender: "m" },
        { text: "Ein Kanonier mit Schießpulver unter den Nägeln", type: "soldier", gender: "m" },
        { text: "Eine Kartographin, die Inseln kennt, die es nicht gibt", type: "scholar", gender: "f" },
        { text: "Ein Schiffbrüchiger, der seit Jahren auf einer Insel lebt", type: "civilian", gender: "m" },
        { text: "Der Smutje, der eigentlich ein gefallener Adliger ist", type: "civilian", gender: "m" },
        { text: "Eine Kopfgeldjägerin, die Piraten jagt", type: "soldier", gender: "f" },
        { text: "Ein Navigator, der nach den Sternen segelt", type: "scholar", gender: "m" },
        { text: "Der Kapitän eines Geisterschiffs", type: "undead", gender: "m" },
        { text: "Eine Händlerin, die Schmuggelware liebt", type: "merchant", gender: "f" },
        { text: "Ein alter Fischer, der einen Leviathan gesehen hat", type: "civilian", gender: "m" },
        { text: "Die Wirtin der 'Schwarzen Perle'", type: "civilian", gender: "f" },
        { text: "Ein Voodoo-Priester mit Schrumpfköpfen", type: "mage", gender: "m" },
        { text: "Eine Nixe, die ihre Stimme verloren hat", type: "monster", gender: "f" },
        { text: "Ein Deserteur der Royal Navy", type: "soldier", gender: "m" },
        { text: "Der Gouverneurstochter, die das Abenteuer sucht", type: "noble", gender: "f" },
        { text: "Ein Sklave, der seine Ketten gesprengt hat", type: "civilian", gender: "m" },
        { text: "Eine mysteriöse Frau mit einer Augenklappe", type: "rogue", gender: "f" },
        { text: "Der Wächter des Leuchtturms", type: "official", gender: "m" },
        { text: "Ein Tiefseetaucher in einem schweren Anzug", type: "craftsman", gender: "m" },
        { text: "Eine Heilerin, die Korallen als Medizin nutzt", type: "mage", gender: "f" },
        { text: "Ein Schreiber der Ostindien-Kompanie", type: "scholar", gender: "m" },
        { text: "Der letzte Überlebende einer Meuterei", type: "rogue", gender: "m" },
        { text: "Eine Piratenbraut mit zwei Pistolen", type: "rogue", gender: "f" },
        { text: "Ein Bootsmann, der nie schläft", type: "soldier", gender: "m" },
        { text: "Der König der Diebe von Tortuga", type: "rogue", gender: "m" },
        { text: "Eine alte Frau, die Netze flickt und Schicksale webt", type: "mage", gender: "f" },
        { text: "Ein Mann mit einer Hakenhand und einem freundlichen Lächeln", type: "rogue", gender: "m" },
        { text: "Die Tochter des Meereskönigs (in Verkleidung)", type: "noble", gender: "f" },
        { text: "Ein Kartenspieler, der noch nie verloren hat", type: "rogue", gender: "m" },
        { text: "Ein Affe mit einem kleinen Hut (Begleiter eines toten Piraten)", type: "beast", gender: "m" },
        { text: "Der Geist einer Frau, die am Riff wartet", type: "undead", gender: "f" }
    ],
    items: [
        "eine verfluchte Aztekengold-Münze", "die Karte zur Insel der Toten", "einen Kompass, der nicht nach Norden zeigt",
        "eine Flasche Rum, die nie leer wird", "den schwarzen Fleck", "ein Logbuch voller Lügen",
        "den Schlüssel zur Kapitänskajüte", "eine Flagge, die Angst verbreitet", "ein Fernrohr aus Knochen",
        "eine Perle so groß wie ein Auge", "den Dreizack eines Meermannes", "eine Kiste mit spanischem Silber",
        "ein Stück vom Tau des Geisterschiffs", "eine Kanonenkugel mit Runen", "den Hut des Piratenkönigs",
        "eine Flaschenpost aus der Zukunft", "ein goldenes Steuerad", "den zahmen Affen des Kapitäns",
        "eine Galionsfigur, die weint", "einen Haken aus purem Silber",
        "ein Kompass aus Elfenbein", "eine Kiste voller Musketen", "den Ehering einer Geisterbraut",
        "eine Schatztruhe, die beißt", "ein Stück Koralle, das leuchtet", "die Pfeife des Kapitäns",
        "ein Buddelschiff mit einem echten Schiff darin", "eine Seekarte aus Menschenhaut", "einen Dolch aus Walzahn",
        "eine Laterne, die Geister zeigt", "ein Netz aus goldenem Garn", "eine Flöte, die Stürme ruft",
        "den Zahn eines Kraken", "eine Augenklappe, die durch Wände sieht", "ein Fass Schießpulver (nass?)",
        "den Siegelring des Gouverneurs", "eine Kette aus Haifischzähnen", "ein Buch über Seeungeheuer",
        "eine Muschel, die flüstert", "den Kompass von Captain Jack", "eine Machete mit Gravur",
        "ein Paar Stiefel, die auf Wasser gehen", "eine Hängematte aus Seide", "den Anker einer Galeone",
        "eine Kiste mit exotischen Gewürzen", "ein Fernrohr, das in die Vergangenheit sieht",
        "den Schlüssel zum Leuchtturm", "eine Glocke vom Meeresgrund", "ein Stück von einem Eisberg (schmilzt nie)",
        "das Herz von Davy Jones (angeblich)", "eine Karte zu Atlantis", "einen Sextanten aus Gold"
    ],
    locations: [
        "auf der Totenkopfinsel", "in der Spelunke 'Zum Blutigen Anker'", "im Bauch des Walfischs",
        "auf dem Wrack der stolzen Galeone", "in der Schmugglerbucht", "auf dem höchsten Mast",
        "in der Grotte der Nixen", "auf dem Marktplatz von Tortuga", "im Kerker der Festung",
        "auf einer einsamen Sandbank", "im Bermuda-Dreieck", "in der Kapitänskajüte",
        "am Riff der Verdammnis", "im Dschungel der tausend Augen", "unter dem Wasserfall",
        "in der Lagune der Haie", "auf dem verlassenen Leuchtturm", "in der Werft",
        "auf dem Sklavenmarkt", "im Pulvermagazin",
        "in der Kajüte des Admirals", "auf dem Ausguck", "im überfluteten Tempel",
        "in der Taverne 'Zum Einbeinigen'", "am Strand der Gebeine", "im Kielraum",
        "auf einer schwimmenden Festung", "in der Werft der Verdammten", "am Ende der Welt",
        "in der Bucht der Schiffbrüchigen", "im Strudel des Verderbens", "auf der Geisterinsel",
        "im Korallenriff", "in der Unterwasserstadt", "am Pier bei Nacht",
        "im Lagerhaus der Ostindien-Kompanie", "in der Hängematte", "an der Steilküste",
        "in der Grotte des Schreckens", "auf dem Deck der 'Flying Dutchman'", "im Netz eines Riesenkraken",
        "in der Kombüse", "in der Offiziersmesse", "im Laderaum voller Ratten",
        "auf einer einsamen Palmeninsel", "im Auge des Taifuns", "in der Schatzkammer des Gouverneurs"
    ],
    targets: [
        "den legendären Weißen Wal", "den Geist von Captain Kidd", "einen Verräter in der Crew",
        "die Tochter des Gouverneurs", "den Kraken", "das Geisterschiff",
        "einen rivalisierenden Piratenfürsten", "die Meerhexe", "einen Schatzsucher",
        "den königlichen Steuereintreiber", "einen Meermann", "den Leviathan",
        "den Koch, der das Essen vergiftet hat", "den Papagei, der zu viel weiß", "den Geisterkapitän",
        "den Admiral der Flotte", "den Wächter des Schatzes", "eine Riesenschildkröte",
        "den stummen Navigator", "die Sirenen-Königin", "den Mann im Mond (Wahnvorstellung?)",
        "den Verräter", "den Spion der Krone", "die Hexe des Westwindes",
        "den untoten Bootsmann", "den Riesenkraken", "den weißen Hai",
        "die Galionsfigur (lebendig?)", "den letzten ehrlichen Mann", "den Kartraphen",
        "den 'Roten Korsaren'", "die 'Schwarze Witwe'", "den Gouverneur",
        "die Nixe, die nicht singt", "das Seeungeheuer", "den Fliegenden Holländer"
    ],
    task_templates: [
        "##Item## ##Location## zu bergen",
        "den Schatz ##Location## zu vergraben",
        "das Schiff ##Location## zu kapern",
        "##Target## ##Location## über die Planke gehen zu lassen",
        "einen Pakt mit ##Target## ##Location## zu schließen",
        "##Item## von ##Target## ##Location## zu stehlen",
        "die Karte zu ##Location## zu finden",
        "eine Meuterei ##Location## anzuzetteln",
        "##Target## ##Location## vor der Marine zu warnen",
        "den Fluch über ##Item## ##Location## zu brechen",
        "##Target## ##Location## zu einem Trinkduell herauszufordern",
        "##Item## ##Location## gegen Rum zu tauschen",
        "das Wrack ##Location## zu plündern",
        "##Item## ##Location## über Bord zu werfen",
        "##Target## ##Location## vor dem Ertrinken zu retten",
        "##Item## ##Location## zu hissen (unauffällig)",


        // --- Social / Intrigue ---
        "die Crew gegen ##Target## ##Location## aufzuwiegeln",
        "sich als reicher Kaufmann auszugeben, um ##Target## ##Location## anzulocken",
        "ein Gerücht über einen Fluch ##Location## zu streuen, um Konkurrenten fernzuhalten",
        "den Papagei von ##Target## ##Location## zu bestechen (mit Crackern)",
        "einen falschen Schatzplan an ##Target## ##Location## zu verkaufen",
        "ein Bündnis mit den Meerjungfrauen ##Location## zu schmieden",


        // --- Reverse / Morally Grey ---
        "das Schiff von ##Target## ##Location## zu sabotieren (Löcher bohren)",
        "die Vorräte ##Location## zu vergiften",
        "##Target## ##Location## an die Royal Navy zu verraten",
        "ein unschuldiges Schiff ##Location## zu kapern",
        "den Leuchtturm ##Location## zu löschen, um Schiffe auflaufen zu lassen",
        "eine Meuterei anzuführen, um den Kapitän ##Location## abzusetzen",


        // --- Detective / Mystery ---
        "das Rätsel der Schatzkarte ##Location## zu lösen",
        "den Verräter in der Crew ##Location## zu enttarnen",
        "herauszufinden, wer den Rum ##Location## gestohlen hat",
        "die Bedeutung des schwarzen Flecks bei ##Target## ##Location## zu ergründen",
        "den Geisterkapitän ##Location## zu befragen",
        "die Herkunft von ##Item## ##Location## zu bestimmen",


        // --- Pirate Specific (Sea & Curse) ---
        "einen Voodoo-Fluch ##Location## zu wirken",
        "das Schiff durch den Sturm ##Location## zu navigieren",
        "einen Kraken ##Location## zu beschwören",
        "nach ##Item## am Meeresgrund ##Location## zu tauchen",
        "ein Würfelspiel gegen einen Dämon ##Location## zu gewinnen",
        "eine Flaschenpost ##Location## zu versiegeln und abzusenden",
        "den 'Grünen Blitz' am Horizont ##Location## einzufangen",
        "ein Geisterschiff ##Location## zu entern",
        "durch den 'Strudel des Todes' ##Location## zu steuern",
        "einen Walfänger ##Location## zu sabotieren",
        "die Glocke vom Grund des Ozeans ##Location## zu bergen",
        "einem Meerjungfrauen-Gesang ##Location## zu widerstehen",
        "die Flagge der Royal Navy ##Location## zu stehlen",
        "ein Duell auf der Rah eines Mastes ##Location## auszufechten",
        "eine Schatzkiste ##Location## zu öffnen, ohne den Fluch auszulösen",
        "den 'Schwarzen Fleck' an ##Target## ##Location## weiterzugeben",
        "eine Partie 'Liar's Dice' ##Location## um das eigene Leben zu spielen",
        "einen Handel mit ##Target## ##Location## einzugehen",
        "##Item## ##Location## zu schmuggeln",
        "das Schiff ##Location## auf Kiel zu legen (reparieren)",
        "##Target## ##Location## zu fesseln und zu knebeln",
        "##Item## ##Location## zu hissen (Flagge)"
    ],
    reasons: [
        "um König der Piraten zu werden", "für Gold und Ruhm", "um einen alten Fluch zu brechen",
        "aus Rache an der Royal Navy", "um die Crew zu retten", "weil der Rum alle ist",
        "um einer Zwangsheirat zu entkommen", "um die Gunst der Meerhexe zu gewinnen", "für eine Flasche voll Wind",
        "um nicht als Haifischfutter zu enden", "weil der Kapitän es befiehlt", "um eine Wette zu gewinnen",
        "um den Schatz zu finden", "um die Freiheit zu genießen", "um der Legende gerecht zu werden",
        "weil die Sterne es sagen", "um einen Blutsbruder zu rächen", "um die Schulden zu bezahlen"
    ],
    incidents: [
        "Ein Sturm zieht auf, der nach Schwefel riecht", "Das Meer färbt sich blutrot",
        "Der Kraken wurde gesichtet", "Die Toten erheben sich aus der Brandung",
        "Ein Geisterschiff erscheint im Nebel", "Die Kompassnadel dreht sich wild",
        "Die Ratten verlassen das Schiff", "Ein unheimliches Leuchten unter dem Kiel",
        "Der Papagei spricht plötzlich mit der Stimme des Vaters", "Das Wasser verwandelt sich in Wein (oder Blut?)",
        "Ein Gesang, der alle in den Schlaf wiegt", "Feuer an Deck!",
        "Die Segel reißen ohne Wind", "Ein Mann geht über Bord",
        "Die Kanonen feuern von selbst", "Nebel, der Stimmen hat"
    ],
    deadlines: [
        "bevor die Flut kommt", "bevor der Galgen steht", "wenn die Gezeiten wechseln",
        "bevor die Marine eintrifft", "bevor der Fluch wirkt", "beim ersten Kanonenschuss",
        "bevor der Morgen graut", "solange der Wind günstig steht",
        "bevor der Rum ausgeht", "wenn der Mond am höchsten steht", "bevor der Kraken erwacht"
    ]
};
