
export const QUEST_DATA_SPACE_DE = {
    givers: [
        { text: "Ein Alien-Botschafter mit drei Augen", type: "official", gender: "m" },
        { text: "Eine Sternenflotten-Kapitänin", type: "official", gender: "f" },
        { text: "Ein Cyborg-Söldner mit verrosteten Implantaten", type: "soldier", gender: "m" },
        { text: "Eine KI, die sich als Kind projiziert", type: "construct", gender: "u" },
        { text: "Ein Xenobiologe, der fasziniert von Schleim ist", type: "scholar", gender: "m" },
        { text: "Ein Schmuggler, der 'Kessel-Flug' erwähnt", type: "rogue", gender: "m" },
        { text: "Die Matriarchin eines sterbenden Planeten", type: "noble", gender: "f" },
        { text: "Ein Roboter, der Gefühle simulieren will", type: "construct", gender: "m" },
        { text: "Ein Minenarbeiter von einem Asteroiden", type: "civilian", gender: "m" },
        { text: "Eine Kopfgeldjägerin in mandalorianischer Rüstung", type: "soldier", gender: "f" },
        { text: "Ein Technopriester, der Maschinen salbt", type: "cleric", gender: "m" },
        { text: "Ein Pilot, der behauptet, die Erde gesehen zu haben", type: "civilian", gender: "m" },
        { text: "Eine Kreatur aus reiner Energie", type: "elemental", gender: "u" },
        { text: "Der Administrator der Raumstation", type: "official", gender: "m" },
        { text: "Ein Telepath, der Gedanken liest", type: "mage", gender: "m" },
        { text: "Ein Navigator, der die Sterne singen hört", type: "mage", gender: "m" },
        { text: "Eine abtrünnige Wissenschaftlerin", type: "scholar", gender: "f" },
        { text: "Ein Händler für exotische Genetik", type: "merchant", gender: "m" },
        { text: "Die letzte Überlebende eines toten Sterns", type: "noble", gender: "f" },
        { text: "Ein Droide, der sich für einen Gott hält", type: "construct", gender: "m" },
        { text: "Ein Soldat der galaktischen Garde", type: "soldier", gender: "m" },
        { text: "Eine Hackerin, die das Netzwerk kontrolliert", type: "rogue", gender: "f" },
        { text: "Ein Mönch, der die Leere anbetet", type: "cleric", gender: "m" },
        { text: "Ein Waffenschmied für illegale Plasma-Waffen", type: "craftsman", gender: "m" },
        { text: "Die Wirtin der 'Bar am Ende des Universums'", type: "civilian", gender: "f" },
        { text: "Ein Zeitreisender, der den falschen Tag erwischt hat", type: "scholar", gender: "m" },
        { text: "Ein Klon, der seine Ursprungs-DNA sucht", type: "civilian", gender: "m" },
        { text: "Eine Gestaltwandlerin, die ihre Form vergessen hat", type: "monster", gender: "f" },
        { text: "Ein Schrottsammler im Weltraum-Anzug", type: "rogue", gender: "m" },
        { text: "Eine Psionikerin, die Gläser zerspringen lässt", type: "mage", gender: "f" },
        { text: "Ein Admiral, der einen Putsch plant", type: "official", gender: "m" },
        { text: "Der Hüter des galaktischen Zoos", type: "druid", gender: "m" },
        { text: "Ein Attentäter, der unsichtbar ist", type: "rogue", gender: "m" },
        { text: "Eine Archäologin für Pre-Warp-Zivilisationen", type: "scholar", gender: "f" },
        { text: "Ein Pilot, dessen Schiff lebt", type: "civilian", gender: "m" },
        { text: "Ein Mutant aus den unteren Ebenen", type: "monster", gender: "m" },
        { text: "Die Stimme des Schiffscomputers (Hologramm)", type: "construct", gender: "f" },
        { text: "Ein Diplomat, der nur in Rätseln spricht", type: "official", gender: "m" },
        { text: "Eine Plünderin von Schlachtfeldern", type: "rogue", gender: "f" },
        { text: "Ein Mann, der aus Kryo-Schlaf erwacht ist (nach 1000 Jahren)", type: "civilian", gender: "m" },
        { text: "Ein Wesen, das aus Kristallen besteht", type: "elemental", gender: "u" },
        { text: "Der Mechaniker, der Wunder vollbringt", type: "craftsman", gender: "m" },
        { text: "Eine Spionin des Imperiums", type: "soldier", gender: "f" },
        { text: "Ein Priester der Maschinen-Gottheit", type: "cleric", gender: "m" },
        { text: "Ein Glücksspieler mit einem kybernetischen Auge", type: "rogue", gender: "m" }
    ],
    items: [
        "ein instabiler Plasma-Kern", "der Hyperantrieb-Schlüssel", "ein antikes Jedi-Artefakt",
        "eine verschlüsselte Daten-Disc", "eine Probe des 'Xenomorph-Schleims'", "ein Kommunikator, der nur Rauschen empfängt",
        "die Baupläne des Todessterns (Teil 1)", "ein Phasen-Blaster", "eine Flasche romulanisches Ale",
        "ein Splitter eines Meteoriten", "der Neuro-Chip eines Androiden", "eine Karte der Unbekannten Regionen",
        "ein Holocron", "eine Batterie, die ewig hält", "ein Anzug gegen Vakuum",
        "ein lebender Tribble", "ein Universal-Übersetzer", "ein Stück Dunkle Materie",
        "ein Lichtschwert (beschädigt)", "ein Würfel, der holografische Karten zeigt", "ein Gravitations-Generator",
        "die Blackbox eines verschollenen Schiffs", "eine Phiole mit Nanobots", "ein Helm eines toten Soldaten",
        "ein Kristall, der singt", "eine Waffe, die keine Munition braucht", "ein tragbares Schutzschild",
        "ein Medikit aus der Zukunft", "ein Buch aus echtem Papier (extrem wertvoll)", "ein Samen eines außerirdischen Baumes",
        "ein Handschuh, der Elektrizität steuert", "ein Ring, der teleportiert (zufällig)", "eine Dose 'Echte Luft'",
        "ein Steuerknüppel aus Gold", "der Kopf eines Droiden (spricht noch)", "eine Kiste mit Antimaterie (Vorsicht!)",
        "ein Passierschein A38", "eine Uniform des Feindes", "ein Scanner, der Lügen erkennt",
        "ein Stück Rumpfpanzerung (unzerstörbar?)", "eine Alien-Larve im Glas", "ein Dolch aus Licht",
        "ein Implantat, das Erinnerungen speichert", "eine Sternenkarte aus Glas", "ein Ring aus Neutronium"
    ],
    locations: [
        "auf der Mondbasis Alpha", "im Orbit um den Saturn", "im Wrack des Kolonieschiffs",
        "auf dem Wüstenplaneten", "in der Bar am Ende des Universums", "im Maschinenraum",
        "auf der Brücke des Kreuzers", "in der Schwerelosigkeits-Kammer", "im Wurmloch",
        "auf dem Asteroidenfeld", "in der Xenobiologie-Station", "im Hangar 18",
        "auf dem Eisplaneten Hoth (ähnlich)", "in der Biosphäre", "im Replikator-Raum",
        "in der medizinischen Bucht", "im Frachtraum", "im Teleporter-Raum",
        "in der Luftschleuse", "im Kern des Reaktors", "auf der Aussichtsplattform",
        "in den Minen des roten Planeten", "im Nebel des Grauens", "auf einer Dyson-Sphäre",
        "in der verlassenen Raumstation", "im Hyperraum-Tunnel", "auf dem Schrottplatz der Sterne",
        "in der Bibliothek von Alexandria (Digital)", "im Simulator-Raum", "in der Offiziersmesse",
        "auf der Oberfläche eines Kometen", "im Zentrum der Galaxie", "am Ereignishorizont",
        "in der Werft von Utopia Planitia", "im Quarantäne-Bereich", "in der Rettungskapsel",
        "auf dem Marktplatz von Coruscant (ähnlich)", "in der Wolkenstadt", "im Sumpf von Dagobah (ähnlich)",
        "in der Arena der Gladiatoren", "im Labor des Verrückten", "in der Schaltzentrale des Todessterns",
        "im Schlafsaal der Klone", "im Lüftungsschacht", "unter der Oberfläche des Eismondes"
    ],
    targets: [
        "die Schwarmkönigin", "eine abtrünnige KI", "den Schmugglerkönig",
        "einen Formwandler", "den Imperator", "einen Weltraumpiraten",
        "das schwarze Loch (Kollaps verhindern)", "eine außerirdische Spore", "den Verräter an Bord",
        "eine feindliche Flotte", "den Ersten Offizier", "einen Zeitreisenden",
        "den Kopfgeldjäger", "das Alien-Baby", "den verrückten Wissenschaftler",
        "den Großadmiral", "den Symbionten", "den Cyborg-Ninja",
        "den Hacker 'Ghost'", "die Wächter-Drohne", "den letzten Jedi (oder Sith?)",
        "den Händler des Todes", "die Spionin", "den Diplomaten",
        "das Mutterschiff", "den Planetenfresser", "den Sternenwanderer",
        "das Orakel", "den Warlord", "die Königin der Borg (ähnlich)",
        "den Klon-Krieger", "das Experiment 626", "den Schrottsammler",
        "den Telepathen", "den Unsichtbaren"
    ],
    task_templates: [
        "##Item## ##Location## zu bergen",
        "die Sensoren ##Location## zu kalibrieren",
        "einen Erstkontakt mit ##Target## ##Location## herzustellen",
        "##Item## ##Location## zu scannen",
        "##Target## ##Location## zu neutralisieren",
        "eine diplomatische Krise mit ##Target## ##Location## zu lösen",
        "##Item## vor der Selbstzerstörung ##Location## zu retten",
        "einen Notruf ##Location## zu untersuchen",
        "##Target## ##Location## durch die Luftschleuse zu werfen",
        "##Item## ##Location## in den Reaktor zu werfen",
        "die Schilde ##Location## zu aktivieren",
        "den Kurs ##Location## zu berechnen",
        "##Target## ##Location## zu extrahieren (beamen)",
        "die Kommunikation mit ##Target## ##Location## wiederherzustellen",
        "##Item## ##Location## zu sabotieren",
        "##Target## ##Location## vor einem Vakuum-Leck zu retten",
        "den Code für ##Item## ##Location## zu hacken",
        "##Target## ##Location## zu klonen (oder das Klonen zu verhindern)",
        "eine Invasion durch ##Target## ##Location## zu stoppen",
        "##Item## ##Location## in den Hyperraum zu schießen",


        // --- Social / Intrigue ---
        "einen diplomatischen Skandal mit ##Target## ##Location## zu provozieren",
        "sich als Sternenflotten-Offizier zu tarnen, um ##Target## ##Location## zu täuschen",
        "eine geheime Allianz mit ##Target## ##Location## zu schmieden",
        "die Kommunikation von ##Target## ##Location## abzuhören",
        "##Target## ##Location## davon zu überzeugen, die Seiten zu wechseln",
        "ein Friedensabkommen ##Location## zu sabotieren",


        // --- Reverse / Morally Grey ---
        "Schmuggelware ##Location## zu verstecken, um ##Target## zu belasten",
        "einen Sabotageakt ##Location## zu begehen und ##Target## die Schuld zu geben",
        "die Notfall-Rationen ##Location## zu stehlen",
        "##Target## ##Location## an Kopfgeldjäger zu verraten",
        "ein gefährliches Alien ##Location## freizulassen",
        "den Sauerstoff ##Location## knapp werden zu lassen",


        // --- Detective / Mystery ---
        "das Logbuch von ##Item## ##Location## zu entschlüsseln",
        "den Ursprung des Notsignals ##Location## zu ermitteln",
        "die biochemischen Spuren von ##Target## ##Location## zu analysieren",
        "herauszufinden, wer den Reaktor ##Location## sabotiert hat",
        "das Schicksal der verschollenen Crew ##Location## aufzuklären",
        "ein Zeit-Paradoxon ##Location## zu untersuchen",


        // --- Space Specific (Tech & Void) ---
        "den Warpantrieb ##Location## mit ##Item## zu reparieren",
        "ein Schwarzes Loch ##Location## zu stabilisieren",
        "die Schilde von ##Location## zu modulieren, um Strahlung zu blocken",
        "ein Terraforming-Protokoll ##Location## zu initiieren",
        "die Gravitation ##Location## wiederherzustellen",
        "einen Asteroiden ##Location## auf einen neuen Kurs zu bringen",
        "die KI ##Location## von einem Logik-Fehler zu befreien",
        "ein uraltes Relikt ##Location## zu bergen, bevor es zerfällt",
        "den Erstkontakt mit einer neuen Spezies ##Location## zu protokollieren",
        "ein Rennen durch ein Asteroidenfeld ##Location## zu gewinnen",
        "einen Sonnensturm ##Location## zu überleben",
        "die Quarantäne-Station ##Location## zu versiegeln",
        "ein Wurmloch ##Location## zu kartografieren",
        "eine Dyson-Sphäre ##Location## zu scannen",
        "den Schiffscomputer ##Location## neu zu starten (manuell)",
        "eine Rebellion der Droiden ##Location## friedlich zu beenden",
        "ein Vakuum-Leck ##Location## mit improvisierten Mitteln zu schließen",
        "die Koordinaten der 'Verlorenen Erde' ##Location## zu finden"
    ],
    reasons: [
        "für die Föderation", "um den Krieg zu beenden", "um neue Welten zu entdecken",
        "weil der Computer es berechnet hat", "um die Galaxie zu retten", "für Credits",
        "um nach Hause zu telefonieren", "weil der Sauerstoff knapp wird", "um die Zeitlinie zu schützen",
        "gegen das Imperium", "aus wissenschaftlicher Neugier", "um First Contact zu vermeiden",
        "weil die Prophezeiung es sagt", "um den Captain zu beeindrucken", "um einer Strafe zu entgehen",
        "weil der Warpkern bricht", "um die Spezies zu retten", "aus Rache für Alderaan"
    ],
    incidents: [
        "Sensoren spielen verrückt", "Schilde bei 20%", "Eindringlings-Alarm!",
        "Die Schwerkraft fällt aus", "Ein Wurmloch öffnet sich", "Drei Monde stehen in Konjunktion",
        "Der Computer singt 'Daisy Bell'", "Ein unbekanntes Signal wird empfangen",
        "Die Realität flackert (Holodeck-Fehler)", "Zeitschleife entdeckt",
        "Der Sauerstoffgehalt sinkt", "Aliens sind an Bord",
        "Der Reaktor wird kritisch", "Die künstliche Intelligenz rebelliert",
        "Ein Asteroidenschauer trifft das Schiff", "Die Crew halluziniert"
    ],
    deadlines: [
        "bevor der Sauerstoff ausgeht", "bevor der Warpkern bricht", "in 10 Standard-Minuten",
        "bevor die Supernova explodiert", "bevor die Flotte eintrifft", "bevor die Schilde versagen",
        "bevor der Countdown endet", "solange das Portal offen ist",
        "bevor die Lebenserhaltung ausfällt", "wenn die Sonnenfinsternis beginnt", "bevor der Virus sich ausbreitet"
    ]
};
