
export const QUEST_DATA_PIRATE_EN = {
    givers: [
        { text: "A pirate captain with a wooden leg", type: "rogue", gender: "m" },
        { text: "A notorious privateer", type: "rogue", gender: "f" },
        { text: "The quartermaster guarding the maps", type: "rogue", gender: "m" },
        { text: "An old sea dog rambling about monsters", type: "civilian", gender: "m" },
        { text: "A siren who has come ashore", type: "monster", gender: "f" },
        { text: "The governor of the island colony", type: "official", gender: "m" },
        { text: "A shipwright with golden teeth", type: "craftsman", gender: "m" },
        { text: "A fortune teller from the Voodoo district", type: "mage", gender: "f" },
        { text: "A parrot that babbles secrets", type: "beast", gender: "m" },
        { text: "The ghost of a drowned admiral", type: "undead", gender: "m" },
        { text: "A ship's cook whose stew is deadly", type: "civilian", gender: "m" },
        { text: "A figure draped in wet seaweed", type: "monster", gender: "f" },
        { text: "The harbor master who is easily bribed", type: "official", gender: "m" },
        { text: "A gunner with gunpowder under his nails", type: "soldier", gender: "m" },
        { text: "A cartographer knowing islands that don't exist", type: "scholar", gender: "f" },
        { text: "A castaway living on an island for years", type: "civilian", gender: "m" },
        { text: "The galley cook, actually a fallen noble", type: "civilian", gender: "m" },
        { text: "A bounty hunter chasing pirates", type: "soldier", gender: "f" },
        { text: "A navigator sailing by the stars", type: "scholar", gender: "m" },
        { text: "The captain of a ghost ship", type: "undead", gender: "m" },
        { text: "A merchant who loves contraband", type: "merchant", gender: "f" },
        { text: "An old fisherman who saw a leviathan", type: "civilian", gender: "m" },
        { text: "The landlady of the 'Black Pearl'", type: "civilian", gender: "f" },
        { text: "A Voodoo priest with shrunken heads", type: "mage", gender: "m" },
        { text: "A mermaid who lost her voice", type: "monster", gender: "f" },
        { text: "A deserter from the Royal Navy", type: "soldier", gender: "m" },
        { text: "The governor's daughter seeking adventure", type: "noble", gender: "f" },
        { text: "A slave who broke his chains", type: "civilian", gender: "m" },
        { text: "A mysterious woman with an eyepatch", type: "rogue", gender: "f" },
        { text: "The lighthouse keeper", type: "official", gender: "m" },
        { text: "A deep-sea diver in a heavy suit", type: "craftsman", gender: "m" },
        { text: "A healer using coral as medicine", type: "mage", gender: "f" },
        { text: "A clerk of the East India Company", type: "scholar", gender: "m" },
        { text: "The last survivor of a mutiny", type: "rogue", gender: "m" },
        { text: "A pirate bride with two pistols", type: "rogue", gender: "f" },
        { text: "A boatswain who never sleeps", type: "soldier", gender: "m" },
        { text: "The King of Thieves of Tortuga", type: "rogue", gender: "m" },
        { text: "An old woman mending nets and weaving fates", type: "mage", gender: "f" },
        { text: "A man with a hook hand and a friendly smile", type: "rogue", gender: "m" },
        { text: "The Sea King's daughter (in disguise)", type: "noble", gender: "f" },
        { text: "A gambler who has never lost", type: "rogue", gender: "m" },
        { text: "A monkey with a small hat (dead pirate's companion)", type: "beast", gender: "m" },
        { text: "The ghost of a woman waiting at the reef", type: "undead", gender: "f" }
    ],
    items: [
        "a cursed Aztec gold coin", "the map to the Isle of the Dead", "a compass that doesn't point north",
        "a bottle of rum that never runs empty", "the Black Spot", "a logbook full of lies",
        "the key to the captain's cabin", "a flag that spreads fear", "a spyglass made of bone",
        "a pearl as big as an eye", "a merman's trident", "a chest of Spanish silver",
        "a piece of rope from a ghost ship", "a cannonball with runes", "the Pirate King's hat",
        "a message in a bottle from the future", "a golden ship's wheel", "the captain's tame monkey",
        "a figurehead that weeps", "a hook made of pure silver",
        "an ivory compass", "a crate full of muskets", "a ghost bride's wedding ring",
        "a treasure chest that bites", "a piece of coral that glows", "the captain's pipe",
        "a ship in a bottle with a real ship inside", "a sea chart made of human skin", "a dagger made of whale tooth",
        "a lantern revealing ghosts", "a net of golden yarn", "a flute that summons storms",
        "a kraken's tooth", "an eyepatch that sees through walls", "a barrel of gunpowder (wet?)",
        "the governor's signet ring", "a necklace of shark teeth", "a book about sea monsters",
        "a shell that whispers", "Captain Jack's compass", "an engraved machete",
        "a pair of boots that walk on water", "a hammock made of silk", "a galleon's anchor",
        "a crate of exotic spices", "a spyglass seeing into the past",
        "the lighthouse key", "a bell from the ocean floor", "a piece of an iceberg (never melts)",
        "Davy Jones' heart (allegedly)", "a map to Atlantis", "a sextant made of gold"
    ],
    locations: [
        "on Skull Island", "in 'The Bloody Anchor' dive bar", "inside a whale's belly",
        "on the wreck of the proud galleon", "in Smuggler's Cove", "on the highest mast",
        "in the Mermaid's Grotto", "in the market square of Tortuga", "in the fortress dungeon",
        "on a lonely sandbank", "in the Bermuda Triangle", "in the captain's cabin",
        "at the Reef of Doom", "in the Jungle of a Thousand Eyes", "under the waterfall",
        "in Shark Lagoon", "at the abandoned lighthouse", "in the shipyard",
        "at the slave market", "in the powder magazine",
        "in the admiral's cabin", "in the crow's nest", "in the flooded temple",
        "in the tavern 'The One-Legged Man'", "on the Beach of Bones", "in the bilge",
        "on a floating fortress", "in the Shipyard of the Damned", "at the World's End",
        "in Castaway Bay", "in the Maelstrom of Doom", "on Ghost Island",
        "in the coral reef", "in the underwater city", "on the pier at night",
        "in the East India Company warehouse", "in the hammock", "on the cliffs",
        "in the Cave of Terror", "on the deck of the 'Flying Dutchman'", "in a giant kraken's net",
        "in the galley", "in the officers' mess", "in the cargo hold full of rats",
        "on a lonely palm island", "in the eye of the typhoon", "in the governor's treasury"
    ],
    targets: [
        "the legendary White Whale", "Captain Kidd's ghost", "a traitor in the crew",
        "the governor's daughter", "the Kraken", "the ghost ship",
        "a rival pirate lord", "the Sea Witch", "a treasure hunter",
        "the royal tax collector", "a merman", "the Leviathan",
        "the cook who poisoned the food", "the parrot that knows too much", "the ghost captain",
        "the fleet admiral", "the treasure guardian", "a giant tortoise",
        "the mute navigator", "the Siren Queen", "the Man in the Moon (delusion?)",
        "the traitor", "the Crown's spy", "the Witch of the West Wind",
        "the undead boatswain", "the Giant Kraken", "the Great White Shark",
        "the figurehead (alive?)", "the last honest man", "the cartographer",
        "the 'Red Corsair'", "the 'Black Widow'", "the Governor",
        "the mermaid who doesn't sing", "the sea monster", "the Flying Dutchman"
    ],
    task_templates: [
        "to retrieve ##Item## ##Location##",
        "to bury the treasure ##Location##",
        "to hijack the ship ##Location##",
        "to make ##Target## walk the plank ##Location##",
        "to make a pact with ##Target## ##Location##",
        "to steal ##Item## from ##Target## ##Location##",
        "to find the map to ##Location##",
        "to incite a mutiny ##Location##",
        "to warn ##Target## ##Location## about the Navy",
        "to break the curse of ##Item## ##Location##",
        "to challenge ##Target## to a drinking duel ##Location##",
        "to trade ##Item## for rum ##Location##",
        "to loot the wreck ##Location##",
        "to throw ##Item## overboard ##Location##",
        "to save ##Target## ##Location## from drowning",
        "to strike a bargain with ##Target## ##Location##",
        "to smuggle ##Item## ##Location##",
        "to careen the ship (repair) ##Location##",
        "to bind and gag ##Target## ##Location##",
        "to hoist ##Item## ##Location## (flag)",


        // --- Social / Intrigue ---
        "to incite the crew to mutiny against ##Target## ##Location##",
        "to disguise as a wealthy merchant to lure ##Target## ##Location##",
        "to spread a rumor about a curse ##Location## to keep rivals away",
        "to bribe ##Target##'s parrot ##Location## (with crackers)",
        "to sell a fake treasure map to ##Target## ##Location##",
        "to forge an alliance with the merfolk ##Location##",


        // --- Reverse / Morally Grey ---
        "to sabotage ##Target##'s ship ##Location## (drill holes)",
        "to poison the supplies ##Location##",
        "to betray ##Target## ##Location## to the Royal Navy",
        "to hijack an innocent ship ##Location##",
        "to extinguish the lighthouse ##Location## to run ships aground",
        "to lead a mutiny to depose the captain ##Location##",


        // --- Detective / Mystery ---
        "to solve the riddle of the treasure map ##Location##",
        "to unmask the traitor in the crew ##Location##",
        "to find out who stole the rum ##Location##",
        "to discover the meaning of the Black Spot on ##Target## ##Location##",
        "to question the ghost captain ##Location##",
        "to determine the origin of ##Item## ##Location##",


        // --- Pirate Specific (Sea & Curse) ---
        "to cast a Voodoo curse ##Location##",
        "to navigate the ship through the storm ##Location##",
        "to summon a kraken ##Location##",
        "to dive for ##Item## at the bottom of the sea ##Location##",
        "to win a dice game against a demon ##Location##",
        "to seal and send a message in a bottle ##Location##",
        "to catch the 'Green Flash' on the horizon ##Location##",
        "to hoist ##Item## ##Location## (unnoticed)",
        "to board a ghost ship ##Location##",
        "to steer through the 'Maelstrom of Death' ##Location##",
        "to sabotage a whaler ##Location##",
        "to salvage the bell from the ocean floor ##Location##",
        "to resist a mermaid's song ##Location##",
        "to steal the Royal Navy's flag ##Location##",
        "to fight a duel on the yardarm of a mast ##Location##",
        "to open a treasure chest ##Location## without triggering the curse",
        "to pass the 'Black Spot' to ##Target## ##Location##",
        "to play a game of 'Liar's Dice' ##Location## for one's life"
    ],
    reasons: [
        { text: "to become King of the Pirates" },
        { text: "for gold and glory" },
        { text: "to break an old curse" },
        { text: "for revenge against the Royal Navy" },
        { text: "to save the crew" },
        { text: "because the rum is gone" },
        { text: "to escape a forced marriage" },
        { text: "to win the Sea Witch's favor" },
        { text: "for a bottle full of wind" },
        { text: "to not end up as shark bait" },
        { text: "because the captain commands it" },
        { text: "to win a bet" },
        { text: "to find the treasure" },
        { text: "to enjoy freedom" },
        { text: "to live up to the legend" },
        { text: "because the stars say so" },
        { text: "to avenge a blood brother" },
        { text: "to pay debts" }
    ],
    incidents: [
        { text: "A storm smelling of sulfur approaches" },
        { text: "The sea turns blood red" },
        { text: "The Kraken has been sighted" },
        { text: "The dead rise from the surf" },
        { text: "A ghost ship appears in the fog" },
        { text: "The compass needle spins wildly" },
        { text: "Rats are leaving the ship" },
        { text: "An eerie glow beneath the keel" },
        { text: "The parrot suddenly speaks with father's voice" },
        { text: "Water turns into wine (or blood?)" },
        { text: "A song lulling everyone to sleep" },
        { text: "Fire on deck!" },
        { text: "Sails tear without wind" },
        { text: "Man overboard" },
        { text: "Cannons firing by themselves" },
        { text: "Fog that has voices" }
    ],
    deadlines: [
        { text: "before the tide comes in" },
        { text: "before the gallows are built" },
        { text: "when the tides change" },
        { text: "before the Navy arrives" },
        { text: "before the curse takes effect" },
        { text: "at the first cannon shot" },
        { text: "before dawn breaks" },
        { text: "while the wind is fair" },
        { text: "before the rum runs out" },
        { text: "when the moon is high" },
        { text: "before the Kraken wakes" }
    ]
};
