
export const QUEST_DATA_CYBERPUNK_EN = {
    givers: [
        { text: "A fixer with a chrome arm and sunglasses", type: "rogue", gender: "m" },
        { text: "A netrunner who only speaks via avatars", type: "scholar", gender: "f" },
        { text: "A corporate executive acting nervous", type: "official", gender: "m" },
        { text: "A street doc with a bloody apron", type: "cleric", gender: "m" },
        { text: "A nomad leader on a hoverbike", type: "ranger", gender: "f" },
        { text: "An AI construct of a dead rockstar", type: "undead", gender: "m" },
        { text: "A police detective who knows too much", type: "official", gender: "m" },
        { text: "A drug dealer with synthetic eyes", type: "rogue", gender: "m" },
        { text: "A journalist uncovering a scandal", type: "civilian", gender: "f" },
        { text: "A techie who can fix anything", type: "craftsman", gender: "m" },
        { text: "A fallen idol star with bodyguards", type: "artist", gender: "f" },
        { text: "A mercenary working only for Eurodollars", type: "soldier", gender: "m" },
        { text: "A taxi AI asking philosophical questions", type: "construct", gender: "x" },
        { text: "An unlicensed black market surgeon", type: "healer", gender: "m" },
        { text: "A corporate heiress on the run", type: "noble", gender: "f" },
        { text: "An old hacker still using a keyboard", type: "scholar", gender: "m" },
        { text: "A bartender who knows every secret", type: "civilian", gender: "m" },
        { text: "A cyborg warrior on a vendetta", type: "soldier", gender: "f" },
        { text: "A scavenger finding valuable data", type: "commoner", gender: "m" },
        { text: "A hologram artist with hidden messages", type: "artist", gender: "m" },
        { text: "A smuggler for real food", type: "rogue", gender: "f" },
        { text: "A rogue security droid", type: "construct", gender: "x" },
        { text: "An underground priest of the Neon Church", type: "cleric", gender: "m" },
        { text: "A corporate scientist with a conscience", type: "scholar", gender: "f" },
        { text: "A gang boss with golden teeth", type: "criminal", gender: "m" },
        { text: "An information broker in the Deep Net", type: "rogue", gender: "x" },
        { text: "A street sweeper who sees everything", type: "commoner", gender: "f" },
        { text: "An ex-military working as a bouncer", type: "soldier", gender: "m" },
        { text: "An illegal clone of a celebrity", type: "clone", gender: "x" },
        { text: "A hacker speaking only in code", type: "scholar", gender: "f" },
        { text: "A weapons dealer for experimental tech", type: "merchant", gender: "m" },
        { text: "A courier who never asks questions", type: "rogue", gender: "m" },
        { text: "An activist against cyber-implants", type: "civilian", gender: "f" },
        { text: "A virtual idol that developed consciousness", type: "construct", gender: "f" },
        { text: "An old Yakuza Oyabun in exile", type: "noble", gender: "m" },
        { text: "A street kid with an expensive data chip", type: "child", gender: "x" },
        { text: "A biologist growing illegal plants", type: "scholar", gender: "f" },
        { text: "A bartender at 'Afterlife'", type: "merchant", gender: "m" },
        { text: "A ripperdoc collecting debts", type: "healer", gender: "m" },
        { text: "A corporate spy in disguise", type: "rogue", gender: "f" },
        { text: "A mech pilot without a mech", type: "soldier", gender: "m" },
        { text: "An AI searching for a body", type: "construct", gender: "x" },
        { text: "A dealer for 'Braindance' chips", type: "criminal", gender: "m" },
        { text: "An underground racer", type: "rogue", gender: "f" },
        { text: "A fired security chief", type: "soldier", gender: "m" },
        { text: "A hacker collective (Hive Mind)", type: "group", gender: "x" },
        { text: "An old woman still reading real books", type: "scholar", gender: "f" },
        { text: "A mutant from the sewers", type: "monster", gender: "m" },
        { text: "A corporate auditor 'for special problems'", type: "official", gender: "m" },
        { text: "A bartender who is actually a sleeper agent", type: "rogue", gender: "m" }
    ],
    items: [
        "an experimental bio-chip", "an 'Arasaka MK-IV' cyberdeck", "a data shard with evidence",
        "a bottle of real tequila (priceless)", "the prototype of a new weapon", "a briefcase full of Eurodollars",
        "the access card for Level 99", "a cybernetic eye", "a stolen identity",
        "a 'Black Ice' virus program", "a drone with AI", "a synthetic organ (heart)",
        "codes for the orbital elevator", "a mem-stick from the old days", "a crate of real apples",
        "a neuro-implant with military software", "blueprints for an EMP generator", "a ticket to the Mars colony",
        "an antique pistol (projectile weapon)", "a hacked police radio", "a dose of the 'Eternity' drug",
        "an android head (still speaking)", "a hard drive with compromising data", "a key to a locker",
        "a cloaking device (prototype)", "a nanobot injector", "a crate of illegal cyber-limbs",
        "a virus that drains bank accounts", "a recording of a secret meeting", "an access code for the power grid",
        "a rare vinyl record", "a piece of real sky (hologram)", "a forged passport",
        "a smart gun with its own personality", "a suitcase with a nuclear detonator", "a DNA sample of a CEO",
        "a backup of a dead person's consciousness", "a map of old subway tunnels", "a jammer for surveillance cameras",
        "a bionic arm with a hidden blade", "a can of cat food (luxury item)", "a chip with forbidden music",
        "VR glasses with direct neural link", "a password for a satellite weapon", "a sample of a deadly virus",
        "a suitcase of diamonds (synthetic)", "a list of sleeper agents", "a device to hack vending machines",
        "a jacket with bulletproof weave", "a jet-propelled motorcycle", "a data cube from the first AI"
    ],
    locations: [
        "in Night City (Sector 7)", "in the neon slum 'The Sprawl'", "in the Megatower penthouse",
        "in an illegal ripperdoc clinic", "in Cyberspace (Deep Net)", "in the subway station",
        "in the back room of the Noodle Bar", "in the abandoned factory", "in corporate headquarters",
        "inside the Data Fortress", "on the black market", "at the bio-farm",
        "in the red light district", "at the scrapyard", "in the VR arcade",
        "in the nightclub basement", "on a skyscraper roof", "in the incineration plant",
        "in the server room at zero temperature", "in the quarantine zone", "in a harbor cargo container",
        "in the sewers", "in the Trauma Team waiting room", "in the Grand Hotel lobby",
        "on the highway bridge", "in the abandoned mall", "on the orbital station (via link)",
        "in the secret bunker under the city", "in the android production hall", "in the hydroponic garden",
        "in the police armory", "in the nomad hideout", "in the command center",
        "in the cyber-genetics lab", "in the Yakuza gambling den", "in the rain-slicked backyard",
        "in the capsule apartment", "in the elevator to orbit", "in the cyberware recycling plant",
        "in the club's VIP area", "in the morgue", "in a taxi driving in circles",
        "in the No-Go Zone", "in the nuclear plant on the outskirts", "in the virtual library",
        "in the holodeck", "in the weapons factory", "on the underground highway",
        "at the drone charging station", "in the mayor's office", "in the Ash Desert outside the city"
    ],
    targets: [
        "a rogue AI", "the CEO of Militech", "a cyberpsycho",
        "a rival netrunner", "the Yakuza boss", "a corrupt cop",
        "a corporate assassin", "the leader of the 'Chrome Legion'", "a whistleblower",
        "a synthetic clone being", "the mayor", "a notorious hacker",
        "security drone 'Alpha'", "a mad ripperdoc", "the dealer on the corner",
        "a virtual popstar AI", "the boss of the trash mafia", "a corporate lawyer",
        "an industrial spy", "the leader of the tech cult", "an escaped android",
        "the guardian of the data core", "a black market surgeon", "the nightclub owner",
        "a mercenary leader", "a bioweapon on two legs", "the architect of the Matrix",
        "a ghost in the machine", "the corporate boss's daughter", "a tank out of control",
        "the master thief", "a radical activist", "the last real human",
        "a pack of cyber-dogs", "the surveillance operator", "a nano-swarm",
        "the transport shuttle pilot", "a genetically modified tiger", "the block administrator",
        "a corrupt judge", "the scavenger leader", "a tech shaman",
        "the virus host", "an invisible assassin", "the bomb constructor",
        "a living bomb", "the courier with the code", "the oracle of the Net"
    ],
    task_templates: [
        "to hack ##Item## from the net ##Location##",
        "to extract (kidnap?) ##Target## ##Location##",
        "to smuggle ##Item## ##Location## without being scanned",
        "to upload a virus ##Location##",
        "to 'nullify' ##Target## ##Location##",
        "to acquire information about ##Target## ##Location##",
        "to monitor a deal with ##Target## ##Location##",
        "to retrieve ##Item## ##Location## before corporate troops do",
        "to sabotage the security system ##Location##",
        "to protect ##Target## ##Location## from a cyber attack",
        "to erase the identity of ##Target## ##Location##",
        "to sell ##Item## ##Location## to the highest bidder",
        "to shadow ##Target## ##Location##",
        "to plant a bug on ##Target## ##Location##",
        "to detonate ##Item## ##Location##",
        "to break ##Target## out of prison ##Location##",
        "to overheat the server ##Location##",
        "to replicate ##Item## ##Location##",
        "to extract a confession from ##Target## ##Location##",
        "to ambush the transport of ##Item## ##Location##",
        "to hide ##Target## ##Location## from the Yakuza",
        "to decrypt ##Item## ##Location##",
        "to lay an ambush for ##Target## ##Location##",
        "to blackmail ##Target## ##Location##",
        "to paralyze the network ##Location##",
        "to swap ##Item## ##Location## for a fake",
        "to lure ##Target## into a trap ##Location##",
        "to breach the firewall ##Location##",
        "to find ##Item## in the trash ##Location##",
        "to discredit ##Target## ##Location## (fake news)",
        "to shut down the power ##Location##",
        "to steal ##Item## ##Location##",


        // --- Social / Intrigue ---
        "to spread a false rumor about ##Target## in the Neuro-Net",
        "to disguise as a technician to spy on ##Target## ##Location##",
        "to deliver an encrypted data shard to ##Target## ##Location##",
        "to eavesdrop on ##Target## ##Location## during a meeting with the Triads",
        "to terminate ##Target##'s reputation in the Data Pool",
        "to launch a disinformation campaign against ##Target## ##Location##",
        "to trick ##Target## ##Location## into revealing access codes",


        // --- Reverse / Morally Grey ---
        "to plant fake evidence ##Location## to implicate ##Target##",
        "to help a cyberpsycho ##Location## escape the police",
        "to steal the medication for the orphanage ##Location##",
        "to blackmail ##Target## ##Location## with sensitive data",
        "to cause a system failure ##Location## to cover tracks",
        "to protect an illegal deal ##Location##",
        "to sell ##Target## ##Location## to a corporation",


        // --- Detective / Mystery ---
        "to analyze the digital signature of ##Target## ##Location##",
        "to identify the mole in the corporation ##Location##",
        "to reconstruct the virtual crime scene ##Location##",
        "to hack the connection data of ##Target## ##Location##",
        "to find out who coded the virus ##Location##",
        "to triangulate the source of the signal ##Location##",
        "to restore a corrupt file ##Location##",


        // --- Cyberpunk Specific (Hacking & Tech) ---
        "to inject a daemon into the subnet of ##Location##",
        "to remote control ##Target##'s cyberware ##Location##",
        "to survive a 'Black ICE' attack ##Location##",
        "to upload ##Target##'s consciousness ##Location## onto a chip",
        "to secure an illegal Braindance recording ##Location##",
        "to overwrite the firmware of ##Item## ##Location##",
        "to physically destroy a corp server ##Location##",
        "to free an AI ##Location## from its sandbox",
        "to hack and redirect a flying taxi ##Location##",
        "to repair a cyber-prosthesis ##Location## before it explodes",
        "to perform a memory wipe on ##Target## ##Location##",
        "to turn a drone swarm ##Location## against its owners"
    ],
    reasons: [
        { text: "against the Megacorp" },
        { text: "for the freedom of the Net" },
        { text: "to pay off debts to the Syndicate" },
        { text: "for the next upgrade" },
        { text: "for revenge for a dead partner" },
        { text: "to become famous (Edgerunner)" },
        { text: "to bring the truth to light" },
        { text: "because the system is corrupt" },
        { text: "for the 'big score'" },
        { text: "to survive" },
        { text: "because the fixer wants it" },
        { text: "to escape the police" },
        { text: "for a ticket out of the city" },
        { text: "to cure a disease" },
        { text: "because it's the last job" },
        { text: "out of pure boredom" },
        { text: "to impress someone" },
        { text: "because the voices command it" },
        { text: "to see the world burn" },
        { text: "for a warm meal" },
        { text: "to delete one's own file" },
        { text: "because no one else can do it" },
        { text: "for the honor of the gang" },
        { text: "to embarrass the corporation" },
        { text: "because the AI calculated it" },
        { text: "to recover a lost memory" }
    ],
    incidents: [
        { text: "Network alarm triggered" },
        { text: "Trauma Team is on the way" },
        { text: "Acid rain falls" },
        { text: "Power outage in the whole sector" },
        { text: "A cyberpsycho runs amok" },
        { text: "The police seal off the district" },
        { text: "Your cyberware is being hacked" },
        { text: "A drone is tracking you" },
        { text: "Ads flood your field of vision" },
        { text: "The Yakuza shows up" },
        { text: "The client was murdered" },
        { text: "Your vehicle was stolen" },
        { text: "The target is already dead" },
        { text: "A rival shows up" },
        { text: "The building is collapsing" },
        { text: "An earthquake shakes the city" },
        { text: "The AI takes control" },
        { text: "A virus inspects your systems" },
        { text: "The door is locked" },
        { text: "Poison gas leaks out" },
        { text: "A sniper is lying in wait" },
        { text: "The black market was busted" },
        { text: "A raid is taking place" },
        { text: "The crowd panics" },
        { text: "A power surge fries electronics" },
        { text: "Gravity fails (locally)" },
        { text: "Holograms come alive (glitch)" },
        { text: "Connection lost" },
        { text: "A bounty has been placed on you" },
        { text: "The escape route is blocked" }
    ],
    deadlines: [
        { text: "before the ICE fries you" },
        { text: "before Trauma Team arrives" },
        { text: "before the virus melts your brains" },
        { text: "before Corporate Security gets here" },
        { text: "before the upload is complete" },
        { text: "until dawn" },
        { text: "before the stock market opens" },
        { text: "before the battery runs out" },
        { text: "in exactly 5 minutes" },
        { text: "before the bomb goes off" },
        { text: "before the ship leaves" },
        { text: "before the evidence is deleted" },
        { text: "before the deal busts" },
        { text: "before backup arrives" },
        { text: "before oxygen runs low" },
        { text: "before the AI locks the system" },
        { text: "before the Senator gives the speech" },
        { text: "as soon as the rain stops" }
    ]
};
